### ISSUE TITLE
Make `Phoenix.HTML.Form.inputs_for/4` work with schemaless changesets

### ISSUE THREAD

**Issue by jadlr** [elixir-ecto/ecto#1915] opened 2017-01-19 14:33 UTC
This has been discussed on IRC:

Currently usage of `inputs_for` with a schemaless changeset raises an exception:

```
** (exit) an exception was raised:
    ** (KeyError) key :__struct__ not found in: %{}
        (phoenix_ecto) lib/phoenix_ecto/html.ex:218: Phoenix.HTML.FormData.Ecto.Changeset.find_inputs_for_type!/2
        (phoenix_ecto) lib/phoenix_ecto/html.ex:35: Phoenix.HTML.FormData.Ecto.Changeset.to_form/4
        (phoenix_html) lib/phoenix_html/form.ex:270: Phoenix.HTML.Form.inputs_for/4
```

off topic: 
Thanks for Elixir, Ecto and Phoenix!

**Comment by josevalim** [comment] 2017-02-04 19:04
I am closing this one because the issue is much deeper than originally expected. We don't allow schemaless changesets on embeds/assocs, so we first need to solve this problem and then tackle this. If someone would like to get started, please go ahead, otherwise it is low priority from our side.

**Closed by josevalim** 2017-02-04 19:04 UTC
Labels: Kind:Feature, Level:Starter

**Comment by kingdomcoding** [comment] 2022-05-14 10:18
I'm curious if there's any update about this?

Also, if I'm going to help, where can I look into to start?
