### ISSUE TITLE
Support subquery with aggregate in select clause

### ISSUE THREAD

**Issue by geofflane** [elixir-ecto/ecto#1677] opened 2016-09-07 21:36 UTC
Subquery's don't seem to support aggregates in the select clauses. This kind of query allows you to do an inner join across a subquery to find the minimum in some group.

e.g.:
```
first_records = from t in App.Tasks,
join: r in assoc(t, :record),
group_by: t.id,
select: [t.id, min(r.sequence)]

select u from App.User,
join: r in assoc(u, :records),
join: first_record in subquery(first_record), on: r.task_id = first_record.id and r.sequence = first_record.sequence
```

Causes an error:
```** (Ecto.QueryError) subquery can only select sources (t) or fields (t.field), got: `min(&1.sequence())` in query:```

I would expect a subquery to allow you to return aggregates to use in join conditions. I had to use a fragment instead.

**Comment by josevalim** [comment] 2016-09-08 07:25
Duplicate of #1616 (the error and the solution are the same).

**Closed by josevalim** 2016-09-08 07:25 UTC
