### ISSUE TITLE
Associated module is not an Ecto schema

### ISSUE THREAD

**Issue by paulo-silva** [elixir-ecto/ecto#4371] opened 2024-02-09 21:32 UTC
### Elixir version

1.16.0

### Database and Version

PostgreSQL 15.2

### Ecto Versions

3.11.1

### Database Adapter and Versions (postgrex, myxql, etc)

postgrex 0.17.4

### Current behavior

While bumping elixir on my project, I noticed while compiling a warning like:

```
warning: invalid association `selection_master` in schema App.Schemas.Schema: associated module App.Schemas.AssocSchema is not an Ecto schema
```

Checking this previous issue: https://github.com/elixir-ecto/ecto/issues/4293 - elixir 1.16 was meant to fix this problem, but some devs are still experiencing this problem.

### Expected behavior

This warn should not happen, like it wasn't when using previous versions of elixir.

**Comment by josevalim** [comment] 2024-02-09 22:18
Hi @paulo-silva. We need a mechanism to reproduce the warning, otherwise there isn't much we can do about it. :(

**Comment by paulo-silva** [comment] 2024-02-09 23:26
> Hi @paulo-silva. We need a mechanism to reproduce the warning, otherwise there isn't much we can do about it. :(

@josevalim that makes sense, I'll try to reproduce it in a project example

**Comment by paulo-silva** [comment] 2024-02-13 14:06
@josevalim I tried to reproduce that in a project example, but I'm unable to; I guess the issue is related to the project size. Is there any chance we can huddle and I can show you the issue in the real project?

I tried the [strategy proposed in slack ecto channel](https://elixir-lang.slack.com/archives/C087B66BY/p1707331753210219?thread_ts=1707316724.658989&cid=C087B66BY) as a temp workaround, but I started getting deadlocks

**Comment by nulian** [comment] 2024-02-20 10:46
Got the same issue after removing another schema. But have it every time I build my project guess for now I just keep my old schemas in it not to break this.

**Comment by nulian** [comment] 2024-02-20 11:00
After some puzzling with this same error for me it was caused by having a module attribute reference to a different schema. Though most of the times it doesn't seem to cause any issues but in 1 case it caused the same error for me.

`@organization_role_id_admin OrganizationRole.admin_role_id()`

**Comment by nulian** [comment] 2024-02-20 12:11
I saw another difference was the has_many was removed from organization_role -> organization_memberships

When I readd the reference it will compile again.

**Comment by JoeriDijkstra** [comment] 2024-03-11 10:35
After changing `@organization_role_id_admin OrganizationRole.admin_role_id()` to a static value it seems to work great: `@organization_role_id_admin "foobar"`

so probably some race condition in the compiler like nulian said.

**Comment by josevalim** [comment] 2024-04-14 06:40
Closing it as #4293 was reopened.

**Closed by josevalim** 2024-04-14 06:40 UTC
Labels: Kind:Bug, Note:Needs more info
