### ISSUE TITLE
Ecto join produces the wrong query

### ISSUE THREAD

**Issue by zacksiri** [elixir-ecto/ecto#4519] opened 2024-10-03 14:23 UTC
### Elixir version

1.15.7

### Database and Version

PostreSQL 16

### Ecto Versions

3.12.3

### Database Adapter and Versions (postgrex, myxql, etc)

postgrex 0.19.1

### Current behavior

```elixir   
 queryable
 |> join(:inner, [c], s in assoc(c, :stack))
 |> join(:inner, [c, s], o in assoc(s, :organization))
 |> join(:inner, [c, s, o], r in assoc(o, :references))
 |> where([c, s, o, r], r.uid == ^reference.uid and r.provider == ^reference.provider)
```

The above produces incorrect query, this is the output of the above.

```
from c0 in Insterra.Blueprints.Component, 
  join: r1 in assoc(c0, :reference), 
  join: s2 in assoc(c0, :stack), 
  join: o3 in assoc(r1, :organization), 
  join: r4 in assoc(s2, :references), 
  where: r1.type == ^"component" and r1.uid in ^["1727962591251479"], where: o3.uid == ^"396" and o3.provider == ^"instellar", select: c0
```

I'm not sure why r1 was included.

### Expected behavior

To get around the problem I have to use the from call to create the query

```elixir
from(
  c in queryable,
  join: s in assoc(c, :stack),
  join: o in assoc(s, :organization),
  join: r in assoc(o, :references),
  where: r.uid == ^reference.uid and r.provider == ^reference.provider
)
```

**Comment by josevalim** [comment] 2024-10-03 14:25
From the looks of it, r0 was included because the component <-> organization associations happens through a reference association.

**Comment by zacksiri** [comment] 2024-10-03 14:26
@josevalim yes sure

```elixir
schema "components" do
    field :catalog_id, :integer, virtual: true
    field :category_name, :string, virtual: true
    field :module_name, :string, virtual: true
    field :module_version, :string, virtual: true
    field :name, :string, virtual: true
    field :uid, :string, virtual: true

    field :type, Ecto.Enum, values: [:dependency, :inferred], default: :dependency
    field :current_state, :string, default: "active"
    field :registration, :string, default: "pending"

    belongs_to :stack, Stack
    belongs_to :preset, Preset

    field :attributes, :map, default: %{}

    belongs_to :parent, __MODULE__

    has_many :children, __MODULE__,
      foreign_key: :parent_id,
      where: [current_state: "active"]

    has_many :deleted_children, __MODULE__,
      foreign_key: :parent_id,
      where: [current_state: "deleted"]

    has_one :reference, __MODULE__.Reference

    timestamps()
  end
```

One thing to note that this was not a problem with ecto 3.10.x it started with ecto 3.11

**Comment by zacksiri** [comment] 2024-10-03 14:35
@josevalim I wanted to mention that the query is called in tandem, IE this query is passed into another query 

```elixir
    from(
      c in queryable,
      join: r in assoc(c, :reference),
      where: r.type == ^reference.type and r.uid in ^reference.uids
    )
```

**Comment by josevalim** [comment] 2024-10-03 14:36
Given it works with `from`, it seems to be something related to how we are pruning bindings? Are any of those a through association? Can you please show us all of the schemas with all of the association changes?

**Comment by zacksiri** [comment] 2024-10-03 14:38
So I have a `filter/2` function like this 

```elixir
  def filter({:organization_reference, reference}, queryable) do
    from(
      c in queryable,
      join: s in assoc(c, :stack),
      join: o in assoc(s, :organization),
      join: r in assoc(o, :references),
      where: r.uid == ^reference.uid and r.provider == ^reference.provider
    )
  end

  def filter({:reference, reference}, queryable) do
    from(
      c in queryable,
      join: r in assoc(c, :reference),
      where: r.type == ^reference.type and r.uid in ^reference.uids
    )
  end
```

And the query is called like this

```elixir
  def list(options) do
    options
    |> Enum.reduce(Component, &Component.filter/2)
    |> Repo.all()
  end
```

So the options will basically chain the query

**Comment by josevalim** [comment] 2024-10-03 15:33
I cannot reproduce this behaviour:

```
Mix.install([:ecto])

defmodule Component do
  use Ecto.Schema

  schema "components" do
    field :catalog_id, :integer, virtual: true
    field :category_name, :string, virtual: true
    field :module_name, :string, virtual: true
    field :module_version, :string, virtual: true
    field :name, :string, virtual: true
    field :uid, :string, virtual: true

    field :type, Ecto.Enum, values: [:dependency, :inferred], default: :dependency
    field :current_state, :string, default: "active"
    field :registration, :string, default: "pending"

    belongs_to :stack, Stack
    belongs_to :preset, Preset

    field :attributes, :map, default: %{}
    has_one :reference, __MODULE__.Reference

    timestamps()
  end
end

defmodule Component.Reference do
  use Ecto.Schema

  schema "component_references" do
    field :provider, :string, default: "instellar"
    field :current_state, :string, default: "active"
    field :uid, :string
    field :type, :string

    belongs_to :component, Component

    timestamps()
  end
end

defmodule Stack do
  use Ecto.Schema

  schema "stacks" do
    field :organization_name, :string, virtual: true

    field :type, Ecto.Enum, values: [:template, :blueprint]
    field :name, :string
    field :current_state, :string, default: "created"
    field :visibility, :string, default: "private"
    field :description, :string
    belongs_to :organization, Accounts.Organization
    timestamps()
  end
end

defmodule Organization do
  use Ecto.Schema

  schema "organizations" do
    field :name, :string
    has_many :references, __MODULE__.Reference
    timestamps()
  end
end

defmodule Organization.Reference do
  use Ecto.Schema

  schema "organization_references" do
    field :provider, :string
    field :uid, :string

    belongs_to :organization, Organization

    timestamps()
  end
end

defmodule Sample do
  def run do
    import Ecto.Query

    IO.inspect(
      Component
      |> join(:inner, [c], s in assoc(c, :stack))
      |> join(:inner, [c, s], o in assoc(s, :organization))
      |> join(:inner, [c, s, o], r in assoc(o, :references))
      |> where([c, s, o, r], r.uid == ^"321" and r.provider == ^"instellar")
    )
  end
end

Sample.run()
```

So if you can provide a complete mechanism to reproduce it, it would be very welcome. Thanks!

**Comment by greg-rychlewski** [comment] 2024-10-03 15:57
Based on this: https://github.com/elixir-ecto/ecto/issues/4519#issuecomment-2391594391

I think you might be applying both filters maybe when you don't want to. When I compare the SQL in the original post to these functions that's what it seems.

**Comment by zacksiri** [comment] 2024-10-04 06:48
@greg-rychlewski yes you are correct, the problem comes with both filters are being applied.

**Comment by greg-rychlewski** [comment] 2024-10-04 09:31
It sounds to bm like it is behaving as expected. Ecto queries are composable so when you start with this:

```elixir
from(
      c in queryable,
      join: r in assoc(c, :reference),
      where: r.type == ^reference.type and r.uid in ^reference.uids
    )
```

and then pass the result of that into

```elixir
 queryable
 |> join(:inner, [c], s in assoc(c, :stack))
 |> join(:inner, [c, s], o in assoc(s, :organization))
 |> join(:inner, [c, s, o], r in assoc(o, :references))
 |> where([c, s, o, r], r.uid == ^reference.uid and r.provider == ^reference.provider)
```

you will get the result you saw, where all the joins and wheres are present. If you'd like the previous joins and wheres to disappear you'd either have to call [this function](https://hexdocs.pm/ecto/Ecto.Query.html#exclude/2) or keep the original `queryable` around and use that instead.

But if I am misunderstanding your issue please let me know.

**Comment by zacksiri** [comment] 2024-10-04 11:44
@greg-rychlewski I guess my concern is this

Let's say I have case 1:
```elixir
  def filter({:organization_reference, reference}, queryable) do
    from(
      c in queryable,
      join: s in assoc(c, :stack),
      join: o in assoc(s, :organization),
      join: r in assoc(o, :references),
      where: r.uid == ^reference.uid and r.provider == ^reference.provider
    )
  end

  def filter({:reference, reference}, queryable) do
    from(
      c in queryable,
      join: r in assoc(c, :reference),
      where: r.type == ^reference.type and r.uid in ^reference.uids
    )
  end

```

And I have case 2:

```elixir
  def filter({:organization_reference, reference}, queryable) do
    queryable
    |> join(:inner, [c], s in assoc(c, :stack))
    |> join(:inner, [c, s], o in assoc(s, :organization))
    |> join(:inner, [c, s, o], r in assoc(o, :references))
    |> where([c, s, o, r], r.uid == ^reference.uid and r.provider == ^reference.provider)
  end

  def filter({:reference, reference}, queryable) do
    from(
      c in queryable,
      join: r in assoc(c, :reference),
      where: r.type == ^reference.type and r.uid in ^reference.uids
    )
  end
```


And I run:
```elixir
queryable = Component

queryable = filter({:organization_reference, reference}, queryable)

filter({:reference, another_reference}, queryable)
```

Should the result for case 1 and 2 be the same? Because currently they're not the same.

**Comment by greg-rychlewski** [comment] 2024-10-04 12:36
Are you able to share a script like in Jose's last post to reproduce the issue? I am having a tough time seeing where the error could be.

**Comment by greg-rychlewski** [comment] 2024-10-04 17:15
Here is a script I made to try to replicate your last question. It seems to me they are the same. Could you compare to what you are trying?

```elixir
Mix.install([:ecto])

defmodule Component do
  use Ecto.Schema

  schema "components" do
    field :catalog_id, :integer, virtual: true
    field :category_name, :string, virtual: true
    field :module_name, :string, virtual: true
    field :module_version, :string, virtual: true
    field :name, :string, virtual: true
    field :uid, :string, virtual: true

    field :type, Ecto.Enum, values: [:dependency, :inferred], default: :dependency
    field :current_state, :string, default: "active"
    field :registration, :string, default: "pending"

    belongs_to :stack, Stack
    belongs_to :preset, Preset

    field :attributes, :map, default: %{}
    has_one :reference, __MODULE__.Reference

    timestamps()
  end
end

defmodule Component.Reference do
  use Ecto.Schema

  schema "component_references" do
    field :provider, :string, default: "instellar"
    field :current_state, :string, default: "active"
    field :uids, {:array, :string}, default: ["uid"]
    field :type, :string, default: "type"

    belongs_to :component, Component

    timestamps()
  end
end

defmodule Stack do
  use Ecto.Schema

  schema "stacks" do
    field :organization_name, :string, virtual: true

    field :type, Ecto.Enum, values: [:template, :blueprint]
    field :name, :string
    field :current_state, :string, default: "created"
    field :visibility, :string, default: "private"
    field :description, :string
    belongs_to :organization, Accounts.Organization
    timestamps()
  end
end

defmodule Organization do
  use Ecto.Schema

  schema "organizations" do
    field :name, :string
    has_many :references, __MODULE__.Reference
    timestamps()
  end
end

defmodule Organization.Reference do
  use Ecto.Schema

  schema "organization_references" do
    field :provider, :string, default: "provider"
    field :uid, :string, default: "uid"

    belongs_to :organization, Organization

    timestamps()
  end
end

defmodule Sample do
  import Ecto.Query

  def filter1({:organization_reference, reference}, queryable) do
    from(
      c in queryable,
      join: s in assoc(c, :stack),
      join: o in assoc(s, :organization),
      join: r in assoc(o, :references),
      where: r.uid == ^reference.uid and r.provider == ^reference.provider
    )
  end

  def filter1({:reference, reference}, queryable) do
    from(
      c in queryable,
      join: r in assoc(c, :reference),
      where: r.type == ^reference.type and r.uid in ^reference.uids
    )
  end

  def filter2({:organization_reference, reference}, queryable) do
    queryable
    |> join(:inner, [c], s in assoc(c, :stack))
    |> join(:inner, [c, s], o in assoc(s, :organization))
    |> join(:inner, [c, s, o], r in assoc(o, :references))
    |> where([c, s, o, r], r.uid == ^reference.uid and r.provider == ^reference.provider)
  end

  def filter2({:reference, reference}, queryable) do
    from(
      c in queryable,
      join: r in assoc(c, :reference),
      where: r.type == ^reference.type and r.uids in ^reference.uids
    )
  end

  def run do

    reference = %Organization.Reference{}
    another_reference = %Component.Reference{}

    queryable1 = Component
    queryable1 = filter1({:organization_reference, reference}, queryable1)
    IO.inspect filter1({:reference, another_reference}, queryable1)

    #Ecto.Query<from c0 in Component, join: s1 in assoc(c0, :stack),
    join: o2 in assoc(s1, :organization), join: r3 in assoc(o2, :references),
    join: r4 in assoc(c0, :reference),
    where: r3.uid == ^"uid" and r3.provider == ^"provider",
    where: r4.type == ^"type" and r4.uid in ^["uid"]>

    queryable2 = Component
    queryable2 = filter2({:organization_reference, reference}, queryable2), queryable2)
    IO.inspect  filter2({:reference, another_reference}, queryable2)

   #Ecto.Query<from c0 in Component, join: s1 in assoc(c0, :stack),
   join: o2 in assoc(s1, :organization), join: r3 in assoc(o2, :references),
   join: r4 in assoc(c0, :reference),
   where: r3.uid == ^"uid" and r3.provider == ^"provider",
   where: r4.type == ^"type" and r4.uids in ^["uid"]>
  end
end

Sample.run()
```

**Comment by zacksiri** [comment] 2024-10-05 02:24
@greg-rychlewski That's strange, Yeah i'll try to see if i can provide some sort of script.

**Comment by greg-rychlewski** [comment] 2024-11-02 17:06
Hi @zacksiri ,

Since we couldn't reproduce the issue for a while, I'm going to close the issue. But if you are able to provide a way for us to reproduce we'll be glad to re-open it. Thanks!

**Closed by greg-rychlewski** 2024-11-02 17:06 UTC
Labels: Kind:Bug
