### ISSUE TITLE
Mix task `ecto.gen.migration` does not use repo passed in `-r` when running the migration

### ISSUE THREAD

**Issue by voughtdq** [elixir-ecto/ecto#2695] opened 2018-09-20 17:59 UTC
### Precheck
- [x] For bugs, do a quick search and make sure the bug has not yet been reported.

### Environment

- [x] Elixir version (elixir -v): 
```
Erlang/OTP 21 [erts-10.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1]

Elixir 1.7.0 (compiled with Erlang/OTP 20)
```
- [x] Database and version: PostgreSQL 9.6.10
- [x] Ecto version (mix deps):
```
* ecto 2.2.10 (Hex package) (mix)
  locked at 2.2.10 (ecto) e7366dc8
  ok
```
- [x] Database adapter and version (mix deps):
```
* postgrex 0.13.5 (Hex package) (mix)
  locked at 0.13.5 (postgrex) 3d931aba
  ok
```
- [x] Operating system: Debian GNU/Linux 9.5 (stretch)

### Current behavior
When running the mix task and selecting `y` to run the migration, the `-r` flag seems to be ignored:

```
dv@garden:/data/repos/accounts$ mix ecto.gen.migration -r Accounts.Repository rename_config_column_to_options
* creating priv/repository/migrations
* creating priv/repository/migrations/20180920173526_rename_config_column_to_options.exs
Do you want to run this migration? [Yn] y
warning: could not find Ecto repos in any of the apps: [:accounts].

You can avoid this warning by passing the -r flag or by setting the
repositories managed by those applications in your config/config.exs:

    config :accounts, ecto_repos: [...]
```

### Expected behavior

The task will use the argument provided for `-r` and run the migration.

**Comment by josevalim** [comment] 2018-09-20 18:05
Thanks @voughtdq! 

Unfortunately I cannot reproduce this locally. I also checked the repo and we have tests for this scenario too: https://github.com/elixir-ecto/ecto/blob/master/test/mix/tasks/ecto.gen.migration_test.exs

What am I missing? :)

**Comment by josevalim** [comment] 2018-09-20 18:11
To clarify, I am using Ecto 2.2.10. Here you can see how it is picking the `-r` option:

```elixir
~/OSS/phoenix/installer/demo[master %]$ mix ecto.gen.migration  rename_config_column_to_options
warning: could not find Ecto repos in any of the apps: [:demo].

You can avoid this warning by passing the -r flag or by setting the
repositories managed by those applications in your config/config.exs:

    config :demo, ecto_repos: [...]

~/OSS/phoenix/installer/demo[master %]$ mix ecto.gen.migration -r Demo.Repo rename_config_column_to_options
* creating priv/repo/migrations
* creating priv/repo/migrations/20180920180832_rename_config_column_to_options.exs
```

Maybe you have an alias in your mix.exs and something else is running? What is the output of your command if you start it with `MIX_DEBUG=1`?

**Comment by voughtdq** [comment] 2018-09-20 18:12
Okay! I know what the problem is. I had originally assumed that adding

`config :accounts, ecto_repos: [...]` is not necessary if I use the `-r` flag, but it looks like I still need to configure it anyway.

**Comment by josevalim** [comment] 2018-09-20 18:12
@voughtdq I don't think you need to configure it anyway. In my run above, i completely remove the config and everything worked. So let's try with MIX_DEBUG=1 and see what is happening. :)

**Comment by voughtdq** [comment] 2018-09-20 18:15
This is the `MIX_DEBUG=1` output:

```
** Running mix loadconfig (inside Accounts.MixProject)
** Running mix ecto.gen.migration another_test_migration -r Accounts.Repository (inside Accounts.MixProject)
** Running mix deps.loadpaths (inside Accounts.MixProject)
** Running mix deps.precompile (inside Accounts.MixProject)
==> catalog
** Running mix compile --no-deps --no-archives-check --no-elixir-version-check --no-warnings-as-errors (inside Catalog.MixProject)
** Running mix loadpaths --no-deps --no-archives-check --no-elixir-version-check --no-warnings-as-errors (inside Catalog.MixProject)
** Running mix compile.all --no-deps --no-archives-check --no-elixir-version-check --no-warnings-as-errors (inside Catalog.MixProject)
** Running mix compile.yecc --no-deps --no-archives-check --no-elixir-version-check --no-warnings-as-errors (inside Catalog.MixProject)
** Running mix compile.leex --no-deps --no-archives-check --no-elixir-version-check --no-warnings-as-errors (inside Catalog.MixProject)
** Running mix compile.erlang --no-deps --no-archives-check --no-elixir-version-check --no-warnings-as-errors (inside Catalog.MixProject)
** Running mix compile.elixir --no-deps --no-archives-check --no-elixir-version-check --no-warnings-as-errors (inside Catalog.MixProject)
** Running mix compile.xref --no-deps --no-archives-check --no-elixir-version-check --no-warnings-as-errors (inside Catalog.MixProject)
** Running mix compile.app --no-deps --no-archives-check --no-elixir-version-check --no-warnings-as-errors (inside Catalog.MixProject)
==> accounts
** Running mix loadpaths another_test_migration -r Accounts.Repository (inside Accounts.MixProject)
** Running mix archive.check another_test_migration -r Accounts.Repository (inside Accounts.MixProject)
** Running mix compile another_test_migration -r Accounts.Repository (inside Accounts.MixProject)
** Running mix compile.all another_test_migration -r Accounts.Repository (inside Accounts.MixProject)
** Running mix compile.yecc another_test_migration -r Accounts.Repository (inside Accounts.MixProject)
** Running mix compile.leex another_test_migration -r Accounts.Repository (inside Accounts.MixProject)
** Running mix compile.erlang another_test_migration -r Accounts.Repository (inside Accounts.MixProject)
** Running mix compile.elixir another_test_migration -r Accounts.Repository (inside Accounts.MixProject)
** Running mix compile.xref another_test_migration -r Accounts.Repository (inside Accounts.MixProject)
** Running mix compile.app another_test_migration -r Accounts.Repository (inside Accounts.MixProject)
* creating priv/repository/migrations
* creating priv/repository/migrations/20180920181403_another_test_migration.exs
Do you want to run this migration? [Yn] y
** Running mix ecto.migrate Elixir.Accounts.Repository (inside Accounts.MixProject)
warning: could not find Ecto repos in any of the apps: [:accounts].

You can avoid this warning by passing the -r flag or by setting the
repositories managed by those applications in your config/config.exs:

    config :accounts, ecto_repos: [...]

```

**Comment by voughtdq** [comment] 2018-09-20 18:41
In your local test, are you running the migration directly from `ecto.gen.migration`? In my case I'm using `ECTO_EDITOR` and immediately applying the migration. 

If I do apply the migration in a second step i.e `mix ecto.gen.migration ...` and then `mix ecto.migrate...` this works as expected.

**Comment by josevalim** [comment] 2018-09-20 18:52
Oh, the migration one had a bug indeed. Fixed in master: https://github.com/elixir-ecto/ecto/commit/f758f9877b1564099e3251287ca6e47b226ee74e

Thanks for the report!

**Closed by josevalim** 2018-09-20 18:52 UTC
