### ISSUE TITLE
Keep type information from schema fields given to `select_merge`

### ISSUE THREAD

**Issue by bencates** [elixir-ecto/ecto#2939] opened 2019-03-11 17:29 UTC
Casting does not appear to work on `select_merge`:

```elixir
defmodule MyApp.Example do
  use Ecto.Schema

  schema "example" do
    field :message, :string
    field :has_message, :boolean, virtual: true
  end
end

MyApp.Repo.insert!(%MyApp.Example{message: "hello, world"})

example =
  MyApp.Repo.one from e in MyApp.Example,
    select_merge: %{has_message: not is_nil(e.message)}

# Under MySQL `example.has_message` will be an integer instead of a boolean.
assert example.has_message == true # FAILS

# This is a comple error.
example =
  MyApp.Repo.one from e in MyApp.Example,
    select_merge: %{has_message: type(not is_nil(e.message), :boolean)}

# This produces a runtime error under MySQL, since it has no native boolean type.
example =
  MyApp.Repo.one from e in MyApp.Example,
    select_merge: %{has_message: type(fragment("? IS NOT NULL", e.message), :boolean)}
```

I don't see that there is a correct way to cast a `select_merge` if the underlying database doesn't directly support the desired types.

_Originally posted by @bencates in https://github.com/elixir-ecto/ecto/issues/2165#issuecomment-471615483_

**Comment by josevalim** [comment] 2019-03-11 17:31
Following up as in the previous issue, what happens if you do:

```elixir
  MyApp.Repo.one from e in MyApp.Example,
    select: %{has_message: not is_nil(e.message)}
````

without `select_merge`. What does it return? A map with an integer or a boolean?

**Comment by bencates** [comment] 2019-03-11 17:33
```
MyApp.Repo.one from e in MyApp.Example,
  select: %{has_message: not is_nil(e.message)}
```

returns a bare map of `%{has_message: 0}`

**Comment by josevalim** [comment] 2019-03-11 17:40
Ok, so the issue is not related to select_merge, rather that the type information that not/is_nil return a boolean is being lost. :)

**Comment by bencates** [comment] 2019-03-11 17:49
If this helps:

```ecto
MyApp.Repo.one from e in MyApp.Example,
  select: %{has_message: ^true}
# => %{has_message: 1}

MyApp.Repo.one from e in MyApp.Example,
  select: %MyApp.Example{has_message: ^true}
# => %MyApp.Example{message: nil, has_message: 1}
```

**Comment by bencates** [comment] 2019-04-03 21:02
Respectfully, I'm not sure this actually addresses the root issue.

**Comment by josevalim** [comment] 2019-04-03 21:05
Tell me more. :)

Btw, it should address most cases except the one were true/false are directly interpolated as in such case we don't get any information from the query nor any information from the database, but you can always do `not not ^foo`.

**Comment by bencates** [comment] 2019-04-03 21:09
Respectfully, I'm not certain whether this addresses the root issue.

For example:

```elixir
field :today, :date, virtual: true
MyApp.Repo.one from e in MyApp.Example, select_merge: %{today: fragment("CURDATE()")}
# Expected Date.t; actually String.t

field :today, :decimal, virtual: true
MyApp.Repo.one from e in MyApp.Example, select_merge: %{today: ^0}
# Expected Decimal.t; actually integer

field :today, MyCustomType, virtual: true
MyApp.Repo.one from e in MyApp.Example, select_merge: %{today: ^some_complex_computed_value}
# Expected whatever MyCustomType.load returns; actually ???
```

It appears that the stated type of the virtual field is being ignored.

**Comment by josevalim** [comment] 2019-04-03 21:31
@bencates Good call. There is a completely separate issue than the one fixed which is keeping the field type from select_merge, good call.

**Comment by josevalim** [comment] 2019-06-07 10:27
Oh, those are virtual fields. The query syntax doesn't know about virtual fields, because they don't exist in the database, and that's why there is no mapping between them. If the field is represented, my suggestion is to interpolate the field in Elixir land. I agree this is a bug but the amount of work to fix this is unfortunately quite large, for this reason I will close it as unresolved unless someone wants to give a PR a try, thanks!

**Closed by josevalim** 2019-06-07 10:27 UTC
Labels: Kind:Bug, Level:Advanced, Note:Unresolved

**Comment by josevalim** [comment] 2019-06-07 10:38
One alternative is also to explicitly cast the field:

    MyApp.Repo.one from e in MyApp.Example, select_merge: %{today: type(^"1970-01-01", :date)}
