### ISSUE TITLE
Embedded Schemas not validating decimal scale

### ISSUE THREAD

**Issue by ah0y** [elixir-ecto/ecto#3748] opened 2021-09-16 03:40 UTC
### Environment

* Elixir version (elixir -v): Elixir 1.12.0 (compiled with Erlang/OTP 22)
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): N/A
* Ecto version (mix deps): 3.7
* Database adapter and version (mix deps): N/A
* Operating system: Mac OS

### Current behavior

I have an embedded schema which looks something like this:

```elixir
  embedded_schema do
    field(:id, :id)
    field(:date, :date)
    field(:tx_type, :string)
    field(:price, :decimal, scale: 2)
    field(:quantity, :decimal, scale: 8)
  end
 ```
 
 and when passing in either `"10.123"` for price or `"10.123456789"` for quantity (as either strings or actual Decimals) to my schemas changeset, nothing gets raised as invalid.

### Expected behavior

Decimals that go over a fields defined scale should throw some sort of changeset error. Currently I'm working around this by defining my own parametrized type but it would be cool if ecto changesets could do this validation natively.

**Comment by v0idpwn** [comment] 2021-09-16 04:01
I think that, as types don't support options (only parameterized types do), it is not possible to have this behaviour with the decimal type.

**Comment by ah0y** [comment] 2021-09-16 04:05
> I think that, as types don't support options (only parameterized types do), it is not possible to have this behaviour with the decimal type.

oh you are totally right. I just noticed that I can pass random options to string fields and it not raise an error. is that expected as well?

**Comment by josevalim** [comment] 2021-09-16 08:45
@ah0y that's likely the root cause. I think we were use to validate fields but we removed the validation once we add parameterized types. Perhaps we should keep the validation and skip it only if a parameterized type is given.

**Comment by v0idpwn** [comment] 2021-09-29 07:09
Shall we close this in favor of #3750?
I think it makes intuitive that you can't define type-specific options for non-parameterized types.

**Closed** 2021-09-29 08:05 UTC
