### ISSUE TITLE
Huge memory spike for parallel preload

### ISSUE THREAD

**Issue by sickill** [elixir-ecto/ecto#3295] opened 2020-05-08 12:07 UTC
I've debugged curious case of OOM error in our system and found out that there's unexpected, huge memory spike in certain situations with `Repo.preload`.

### Environment

* Elixir version (elixir -v): 1.9.4, 1.10.2
* Database and version: PostgreSQL 11.7
* Ecto version (mix deps): 3.4.3
* Database adapter and version (mix deps): ecto_sql 3.4.3, postgrex 0.15.3
* Operating system: Linux, macOS

### Current behavior

When ALL of the following are true, the 2nd `Repo.preload` causes memory spike of couple of GB:

1. preload twice (preload again after it was already preloaded)
2. the preloads need to have `[has_many_assoc_for_schema_a: [belongs_to_assoc_for_schema_b: has_many_assoc_for_schema_a]`
3. there's more than 1 top level assoc preloaded
4. preloading is executed concurrently (`in_parallel: true`, _which is default_)

With this you can observe the spike (~1 GB in the minimal example app I link below, and we see 3-5 GB in our system). With explicit `in_parallel: false` there's no mem usage at all, and the 2nd preload is basically a no-op like it should be.

I created a minimal project with `ecto` + `ecto_sql`, with couple of schemas that mimics our setup, which allows reproducing this problem in consistent way: https://github.com/sickill/ecto-preload-bug (instructions on how to trigger and observe the spike are in the README).

The amount of records for the top-level has-many assoc for schema "a" plays a role here, with a handful of records the spike is there but rather not very noticable. As the amount of records grows the spike seems to grow exponential-ish. 

First preload:

<img width="694" alt="single-preload" src="https://user-images.githubusercontent.com/17589/81404128-1633a900-9135-11ea-988f-6654773f9a7f.png">

All data gets preloaded and you can't even see any mem usage change.

Now, when you try to preload again:

<img width="713" alt="double-preload" src="https://user-images.githubusercontent.com/17589/81404187-382d2b80-9135-11ea-8214-1c6fe074c4d3.png">

### Expected behavior

No significant extra memory usage, like with `in_parallel: false` case.

**Comment by amcvitty** [comment] 2020-05-20 13:12
I was intrigued by this, since we had an unexplained memory spike on our server a while back. I'm not sure if my message is going to add much, but...

- I replicated the steps via the github repo
- I notice that the memory is all in the `iex` process itself

<img width="847" alt="Screenshot 2020-05-20 20 41 24" src="https://user-images.githubusercontent.com/7907585/82449226-79322200-9add-11ea-82e9-f5a5ea0a7215.png">

- I notice a :erlang.garbage_collect clears it up. This is me running (I don't mean to suggest this makes the problem any less real. Unless you call GC, the memory stays there, and secondly it looks like it really uses all that memory at some point, so in the situation where you get a couple of these requests happening simultaneously it might be that none of them can complete)

<img width="414" alt="Screenshot 2020-05-20 20 40 53" src="https://user-images.githubusercontent.com/7907585/82449368-b3032880-9add-11ea-9477-cfd3a61ce3e1.png">

- The parallel version of `twice` takes about 10 times as long to run as the `twice_not_in_parallel` version

```
~/d/ecto-preload-bug> iex -S mix
Erlang/OTP 22 [erts-10.6.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]

Interactive Elixir (1.10.0) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> for _ <- 1..5, do: :timer.tc(PreloadBug, :once, [])
[{217921, :ok}, {73794, :ok}, {55639, :ok}, {54505, :ok}, {54770, :ok}]
iex(2)> for _ <- 1..5, do: :timer.tc(PreloadBug, :twice, [])
[{939461, :ok}, {969553, :ok}, {583063, :ok}, {820106, :ok}, {588589, :ok}]
iex(3)> for _ <- 1..5, do: :timer.tc(PreloadBug, :twice_not_in_parallel, [])
[{64426, :ok}, {67241, :ok}, {58815, :ok}, {54584, :ok}, {58423, :ok}]
iex(4)>
```

**Comment by amcvitty** [comment] 2020-05-20 15:33
I did a bit more investigation and recorded some results on a PR to the repo @sickill created
https://github.com/sickill/ecto-preload-bug/pull/1

**Comment by michalmuskala** [comment] 2020-05-20 15:46
What is the erlang version you're using? I wonder if this could be related to https://bugs.erlang.org/browse/ERL-1216

**Comment by amcvitty** [comment] 2020-05-20 15:48
I'm using this: 

andy@Andrews-MacBook-Pro ~/d/ecto-preload-bug> elixir -v
Erlang/OTP 22 [erts-10.6.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.10.0 (compiled with Erlang/OTP 22)

**Comment by amcvitty** [comment] 2020-05-20 16:01
Just upgraded to 23, since that issue linked is marked resolved in 23 (I'm installing via brew). And it seems that the issue is still there:
```
andy@Andrews-MacBook-Pro ~/d/ecto-preload-bug> elixir -v
Erlang/OTP 23 [erts-11.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.10.3 (compiled with Erlang/OTP 22)
```
andy@Andrews-MacBook-Pro ~/d/ecto-preload-bug> iex -S mix < mycommand.exs
iex(10)> ...(10)> ...(10)> ...(10)> ...(10)> ...(10)> ...(10)> ...(10)> ...(10)> ...(10)> ...(10)> ...(10)> ...(10)> ...(10)> ...(10)> ...(10)> 00:00:00.882 [info]  ###### Start ######
00:00:00.882 [info]  ###### Preloading first time ######
00:00:00.888 [info]  running async with 2 assocs
00:00:00.889 [info]  streams started
00:00:00.907 [info]  returning preload assoc
00:00:00.908 [info]  running sync
00:00:00.909 [info]  running sync
00:00:00.912 [info]  returning preload assoc
00:00:00.912 [info]  done running sync
00:00:00.912 [info]  returning preload assoc
00:00:00.912 [info]  done running sync
00:00:00.913 [info]  returning preload assoc
00:00:00.922 [info]  done running async
00:00:00.922 [info]  ###### Preloading second time ######
00:00:00.922 [info]  running async with 2 assocs
00:00:00.922 [info]  streams started
00:00:00.938 [info]  running sync
00:00:00.938 [info]  running sync
00:00:00.949 [info]  returning preload assoc
00:00:00.951 [info]  returning preload assoc
00:00:00.951 [info]  done running sync
00:00:00.951 [info]  returning preload assoc
00:00:00.951 [info]  done running sync
00:00:00.952 [info]  returning preload assoc
00:00:01.979 [info]  done running async
00:00:01.979 [info]  ###### Done ######
nil
iex(11)> ⏎                                                                                                                                                                                                  
andy@Andrews-MacBook-Pro ~/d/ecto-preload-bug>

**Comment by michalmuskala** [comment] 2020-05-20 17:14
Thank you for investigating with the different OTP version

**Comment by sickill** [comment] 2020-05-25 21:15
Erlang version I used to reproduce it:

`Erlang/OTP 22 [erts-10.5.6] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]`

**Closed** 2020-06-14 15:54 UTC

**Comment by sickill** [comment] 2020-06-14 18:55
Thank you ! 😍

**Comment by amcvitty** [comment] 2020-06-15 04:56
Great, thanks @josevalim ! 

Given the investigation I did suggested an issue outside Ecto, I wonder if anyone is looking in the elixir kernel concurrency code to see why the code that was there before performed so badly.
