### ISSUE TITLE
Argument Error inserting to ets in query planner

### ISSUE THREAD

**Issue by aselder** [elixir-ecto/ecto#3331] opened 2020-06-12 20:41 UTC
### Environment

* Elixir version (elixir -v): 1.10.3
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): Postgres 12.3
* Ecto version (mix deps): Ecto. 3.4.2 
* Database adapter and version (mix deps): Postgrex 0.15.3
* Operating system: OS X 10.5.5

### Current behavior
Here's the code being called:

```
repo.stream(Ecto.Query.from(migration_def.old_table(), select: ^migration_def.fields()),
      timeout: :infinity
    )
```
This happened during sustained single threaded volume. 

```
** (ArgumentError) argument error
    (stdlib 3.12.1) :ets.insert_new(#Reference<0.2329986327.1665007617.72438>, {[:all, {:take, %{0 => {:any, [:id, :username, :first_name, :last_name, :nickname, :company, :phone_number, :address_line_1, :address_line_2, :city, :state, :zip, :country_code, :created_at, :updated_at, :address_type, :is_default, :created_at, :updated_at]}}}, {{"addresses", nil}, nil}, {:select, {:&, [], [0]}}], :cache, %{assocs: [], from: {:any, {:source, {"addresses", nil}, nil, [id: :any, username: :any, first_name: :any, last_name: :any, nickname: :any, company: :any, phone_number: :any, address_line_1: :any, address_line_2: :any, city: :any, state: :any, zip: :any, country_code: :any, created_at: :any, updated_at: :any, address_type: :any, is_default: :any, created_at: :any, updated_at: :any]}}, postprocess: {:source, :from}, preprocess: [source: :from], take: [:id, :username, :first_name, :last_name, :nickname, :company, :phone_number, :address_line_1, :address_line_2, :city, :state, :zip, :country_code, :created_at, :updated_at, :address_type, :is_default, :created_at, :updated_at]}, {3971, "SELECT a0.\"id\", a0.\"username\", a0.\"first_name\", a0.\"last_name\", a0.\"nickname\", a0.\"company\", a0.\"phone_number\", a0.\"address_line_1\", a0.\"address_line_2\", a0.\"city\", a0.\"state\", a0.\"zip\", a0.\"country_code\", a0.\"created_at\", a0.\"updated_at\", a0.\"address_type\", a0.\"is_default\", a0.\"created_at\", a0.\"updated_at\" FROM \"addresses\" AS a0"}})
    (ecto 3.4.2) lib/ecto/query/planner.ex:157: Ecto.Query.Planner.cache_insert/3
    (ecto 3.4.2) lib/ecto/query/planner.ex:123: Ecto.Query.Planner.query_with_cache/7
    (ecto 3.4.2) lib/ecto/repo/queryable.ex:29: Ecto.Repo.Queryable.stream/3
    (api_v1 0.1.0) lib/api_v1/data_migration/postgres_migrator.ex:12: ApiV1.DataMigration.PostgresMigrator.migrate/1
    (elixir 1.10.2) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.10.2) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.12.1) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```
### Expected behavior

The query works.

**Comment by josevalim** [comment] 2020-06-12 21:51
Hi @aselder! Quick question: does the error happen consistently on every query or is it happening only from time to time? If it is happening only from time to time, do you see other reports?

**Comment by aselder** [comment] 2020-06-12 23:26
@josevalim It's happening very infrequently. I'd say on the order 1 out of a million queries. I've been writing a migration script to transfer ~7 million rows between DBs. I've probably run the script ~20 times and seen this error 2 or 3 times.

**Comment by josevalim** [comment] 2020-06-13 00:56
This is quite surprising. What is your OTP version?

This command can only fail if the table does not exist and the table doesn’t exist only if the repository process crashed for some reason, but then you should see other failures logged too. I assume there are no other failures however?

**Comment by aselder** [comment] 2020-06-13 01:17
Erlang/OTP 22 [erts-10.7.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Interactive Elixir (1.10.2) - press Ctrl+C to exit (type h() ENTER for help)

**Comment by aselder** [comment] 2020-06-13 01:20
I don't remember seeing any other logged failures, and I've lost the log off my scrollback. If I see it again, I'll take another look.

**Comment by aselder** [comment] 2020-06-15 18:32
@josevalim Just ran into again just now. No other failures before the failure inserting into ets.

[log.txt](https://github.com/elixir-ecto/ecto/files/4782212/log.txt)

**Comment by josevalim** [comment] 2020-06-16 08:44
So the only scenario where `insert_new` can fail is if the table does not exist OR the table is private, which is not the case: https://github.com/elixir-ecto/ecto/blob/93f6465c596d6d4875fac11f72e9669af6a09419/lib/ecto/query/planner.ex#L91

Therefore, there are in my mind only two possible scenarios:

1. There is a bug in the Erlang VM - you could try the latest to see if it has been addressed.

2. The table owner process (which is the ecto repo) is terminating, which doesn't seem to be the case based on your reports. Perhaps, if we want to be double sure there is no other failure, you can run the code with `elixir --logger-sasl-reports true -S mix ...`. That will include other restarts you may have in the app.

**Comment by aselder** [comment] 2020-07-01 18:03
I got another error today, which may or may not be related:

```
17:59:54.969 [error] Task #PID<9355.12560.0> started from #PID<9355.16732.0> terminating
** (stop) exited in: DBConnection.Holder.checkout(#PID<9355.16389.0>, [log: #Function<9.66731207/1 in Ecto.Adapters.SQL>, timeout: :infinity, timeout: 15000, pool_size: 10, pool: DBConnection.ConnectionPool])
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    lib/db_connection/holder.ex:86: DBConnection.Holder.checkout/2
    lib/db_connection.ex:1029: DBConnection.checkout/3
    lib/db_connection.ex:1050: DBConnection.checkout/4
    lib/db_connection.ex:1485: DBConnection.begin/3
    lib/db_connection.ex:829: DBConnection.transaction/3
    (elixir 1.10.3) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.10.3) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.12.1) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: #Function<4.16401342/0 in ApiV1.DataMigration.FullMigration>
    Args: []
** (EXIT from #PID<0.12560.0>) shell process exited with reason: exited in: DBConnection.Holder.checkout(#PID<0.16389.0>, [log: #Function<9.66731207/1 in Ecto.Adapters.SQL.with_log/3>, timeout: :infinity, timeout: 15000, pool_size: 10, pool: DBConnection.ConnectionPool])
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
```

**Comment by josevalim** [comment] 2020-07-01 18:56
Oh, those are definitely related. The only reason this command will fail is because the connection pool is no longer available. So my initial suspicion that the repo supervisor is dying seems to be correct. We just need to understand why it is crashing. Have you tried running it with the `elixir --logger-sasl-reports true -S mix ...` command?

**Comment by josevalim** [comment] 2021-12-26 10:35
Closing this. If there is a mechanism to reproduce this error, please let us know. But as mentioned above, if this is happening, it is mostly because the supervision tree is shutting down.

**Closed by josevalim** 2021-12-26 10:35 UTC
