### ISSUE TITLE
Issue as a library developer

### ISSUE THREAD

**Issue by vinniefranco** [elixir-ecto/ecto#4259] opened 2023-08-10 15:02 UTC
### Elixir version

1.15 or pick the one you want

### Database and Version

Scylla / Cassandra

### Ecto Versions

3.10.3

### Database Adapter and Versions (postgrex, myxql, etc)

Exandra

### Current behavior

It is difficult as an Adapter developer to get the cast params and generated SQL for `Changeset` or `Schema.t` structs when using `insert/delete/update` functions, which is unfortunate as this functionality exists for `all/update_all/delete_all` using https://hexdocs.pm/ecto_sql/Ecto.Adapters.SQL.html#to_sql/3

Solutions:
- Duplicate: There is a lot of logic in `Ecto.Repo.Schema` that we do not want to sync with every point release of `Ecto`. While this is a solution, it feels cumbersome, and dirty.
- Refactor: `Ecto.Repo.Schema` is updated to provide an undocumented function, enabling library developers to get at the generated SQL and params.
- Extend: `Ecto.Adapters.SQL` is updated to support `insert` and friends.
- ???: Perhaps you all have some sort of magic up your sleeve :)

### Expected behavior

`Ecto` should provide an easy way to get at the SQL+params generated when using structs/changesets.

Here's an example of the cheapest approach I could think of, given the current state of `Ecto` https://github.com/vinniefranco/exandra/pull/31/files#diff-86af5508ff8d3ccf29b964353d88304c0a59d1d58a98fd993bc62492369db965R104 tagging @whatyouhide as well.

I greatly appreciate your help!

**Comment by josevalim** [comment] 2023-08-10 16:10
Hi @vinniefranco, I am sorry but the problem is not fully clear to me. I understand you want to get the sql of `insert`/`update`/`delete`, but you did not tell me what for. :)

**Comment by whatyouhide** [comment] 2023-08-10 16:41
@josevalim good question 😉 So, Cassandra/Scylla don't support transactions but they do support *batches*, which are essentially a bunch of queries you send to the server together and that get executed atomically.

Xandra (the driver we use) supports batches with an API that looks like this ([docs](https://hexdocs.pm/xandra/0.17.0/Xandra.Batch.html)):

```elixir
prepared = Xandra.prepare!(conn, "INSERT INTO users (name, age) VALUES (?, ?)")

batch =
  Xandra.Batch.new()
  |> Xandra.Batch.add(prepared, ["Rick", 60])
  |> Xandra.Batch.add(prepared, ["Morty", 14])
  |> Xandra.Batch.add(prepared, ["Jerry", 35])
  |> Xandra.Batch.add("DELETE FROM users WHERE name = 'Jerry'")

Xandra.execute!(conn, batch)
```

We'd like to try and bring this over to the Ecto adapter, in a way where, for example, we can insert _changesets_ rather than SQL+params. Does that make more sense? 🙃

**Comment by vinniefranco** [comment] 2023-08-10 16:45
> Hi @vinniefranco, I am sorry but the problem is not fully clear to me. I understand you want to get the sql of `insert`/`update`/`delete`, but you did not tell me what for. :)

Hah! Whoops! 

So, we want an API like so: https://github.com/vinniefranco/exandra/pull/31/files#diff-12766e3aa7002a380922852fd279f14d363dc15e3ffd6a4f1ab40ce92a04b9d0R184-R187

And we want to get the sql and params without the trick used here: https://github.com/vinniefranco/exandra/pull/31/files#diff-0670c8bc6dada9ff1e0b5116c2ac4475603ee6c1021d148c8fee24a3e8863ecaR148-R158 and https://github.com/vinniefranco/exandra/blob/76b24132b57175f109bcdfae0a979cea254d1908/lib/exandra/connection.ex#L100-L109

**Comment by josevalim** [comment] 2023-08-10 16:47
What is the result of a batch? Does it tell which operation failed and which ones did not? What happens if one fail and the other succeed? The reason why `insert`/`update`/`delete` are more complex is because they are meant to return values that applies to the changeset/schema, do the same apply for batches?

**Comment by whatyouhide** [comment] 2023-08-10 16:48
(context: GitHub is being a bit slow to update for us, so we both commented the same thing)

**Comment by whatyouhide** [comment] 2023-08-10 16:49
@josevalim the result of a batch is always a "void", that is, either the whole thing succeeds (and it's all side effects) or it's successful. `SELECT`s are not even supported in batches. I’m not sure I understand why `INSERT`/`UPDATE`/`DELETE` are more complex when it comes to *generating the SQL* only though. I understand we use `RETURNING` sometimes, but that's still something we can generate in the query no?

**Comment by josevalim** [comment] 2023-08-10 17:03
It is because INSERT/UPDATE/DELETE abstract more operations. They handle constraints, duplicate entries, upserts, etc. So the API Ecto closes over is much larger and has much more functionality. The question is which of those features you actually care about. For example, what happens if you attempt to insert an invalid changeset using batch? Something that does not even emit a query currently? What happens about upserts? There is a large surface area and you would need to specify which of those make sense for batches.

**Comment by josevalim** [comment] 2023-08-10 17:09
Other examples: what about prepare_changes callbacks in Ecto.Changeset? What about associations?

It seems clear to me what you won't be able to provide all Repo.insert/update/delete supports, specially because it may use transactions and it may emit several queries by itself. So I feel you actually want a subset of `Ecto.Repo.insert` and there is then a question of how to expose that.

We can even take a step back: how does your `insert` callback addresses all of these concerns, given you don't have transactions?

**Comment by josevalim** [comment] 2023-08-10 17:20
In any case, I think can think of a workaround for now. We can allow adapters to return `{:ok, values, meta_context}` from insert/update/delete. Ecto.Repo.Schema will put that context inside `schema.__meta__.context`. So you can do this:

    Ecto.Repo.insert(changeset, return_xandra_sql_in_meta_context: true)

It will call your adapter, which can then intercept the option, generate the SQL but, instead of executing it, you return `{:ok, [], xandra_sql}`. If `Ecto.Repo.insert/2` returns `{:ok, struct}` is because it is either a no-op or you will find a sql inside the meta. Ping me @whatyouhide if you want to jump into a call (you are glad to join too Vinnie).

PS: the context was added exactly to provide additional context to adapters.

**Comment by whatyouhide** [comment] 2023-08-10 19:41
@josevalim I'll ping you tomorrow, sounds good. 👍

**Comment by vinniefranco** [comment] 2023-08-16 13:29
Hey, gang. What was the outcome?

**Comment by josevalim** [comment] 2023-09-28 19:44
I will go ahead and close this one. I discussed with @whatyouhide possible paths forward and the ball is on your court. If you need any other guidance, please let me know! :)

**Closed by josevalim** 2023-09-28 19:44 UTC
Labels: Kind:Bug
