### ISSUE TITLE
Support type/2 to customize query return values

### ISSUE THREAD

**Issue by ivan** [elixir-ecto/ecto#1920] opened 2017-01-20 09:21 UTC
When performing a schemaless query on some rows in postgresql with a `timestamp` or `timestamp with timezone` column, Ecto returns a `{{year, month, day}, {hour, min, sec, usec}}` tuple instead of a `DateTime` (or any of the other date types):

```
iex(3)> MachineManager.Repo.all(Ecto.Query.from m in "machines", select: [m.hostname, m.boot_time], where: [hostname: "scale6"])
[["scale6", {{2016, 12, 12}, {14, 31, 2, 176000}}]]
```

This seems like a bug because it's not a very useful date format, and I can't find any place to configure the return type (without making a schema).  Maybe I am wrong, though.  In any case, this is very confusing and I spent some time digging for any sign of hope in the documentation and source code.

```
iex(48)> Postgrex.query!(db, "SELECT hostname, boot_time FROM machines WHERE hostname = 'scale6'", [])
%Postgrex.Result{columns: ["hostname", "boot_time"], command: :select,
 connection_id: 12896, num_rows: 1,
 rows: [["scale6",
   %DateTime{calendar: Calendar.ISO, day: 12, hour: 14,
    microsecond: {176000, 6}, minute: 31, month: 12, second: 2, std_offset: 0,
    time_zone: "Etc/UTC", utc_offset: 0, year: 2016, zone_abbr: "UTC"}]]}
```

### Environment

* Elixir version (elixir -v): `Elixir 1.5.0-dev (508bb7882)`
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): `9.5.5-0ubuntu0.16.04`
* Ecto version (mix deps): ecto 2.1.2
* Database adapter and version (mix deps): postgrex 0.13.0
* Operating system: Ubuntu 16.04.1 LTS

**Comment by ericmj** [comment] 2017-01-20 10:58
I believe this will be fixed when Ecto properly switches over to the new calendar types in Elixir. For now we can't fix it because Ecto supports multiple datetime types and there's no way of knowing which one you want without a schema.

You can try `select: type(m.boot_time, Ecto.DateTime)` to hint to Ecto which type you want.

**Comment by ivan** [comment] 2017-01-20 12:10
That doesn't seem to work, unfortunately.  Adding a `type(m.boot_time, Ecto.DateTime)` results in:

```
# ./build
Compiling 1 file (.ex)

== Compilation error on file lib/machine_manager.ex ==
** (Ecto.Query.CompileError) `type(m.boot_time(), Ecto.DateTime)` is not a valid query expression.

* If you intended to call a database function, please check the documentation
  for Ecto.Query to see the supported database expressions

* If you intended to call an Elixir function or introduce a value,
  you need to explicitly interpolate it with ^
```

**Comment by wojtekmach** [comment] 2017-01-20 12:41
I think `m.boot_time()` is invalid, try `m.boot_time`?

**Comment by ivan** [comment] 2017-01-20 13:00
Indeed, that's what I have in my code :-)

```
Erlang/OTP 19 [erts-8.2.1] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:true]

Compiling 1 file (.ex)
Interactive Elixir (1.5.0-dev) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> import Ecto.Query
Ecto.Query
iex(2)> MachineManager.Repo.all(from m in "machines", select: m.boot_time, where: m.hostname == "scale6")
[{{2016, 12, 12}, {14, 31, 2, 161000}}]
iex(3)> MachineManager.Repo.all(from m in "machines", select: type(m.boot_time, Ecto.DateTime), where: m.hostname == "scale6")
** (Ecto.Query.CompileError) `type(m.boot_time(), Ecto.DateTime)` is not a valid query expression.

* If you intended to call a database function, please check the documentation
  for Ecto.Query to see the supported database expressions

* If you intended to call an Elixir function or introduce a value,
  you need to explicitly interpolate it with ^

    (ecto) expanding macro: Ecto.Query.select/3
           iex:3: (file)
    (ecto) expanding macro: Ecto.Query.where/3
           iex:3: (file)
    (ecto) expanding macro: Ecto.Query.from/2
           iex:3: (file)
```

**Comment by wojtekmach** [comment] 2017-01-20 13:46
Seems like `type` cannot be used in `select` expression. FWIW I was able to reproduce the results you had on hex_web (ecto 2.1.2) codebase:

```elixir
iex> HexWeb.Repo.all(from p in "packages", select: p.inserted_at, limit: 1)
[{{2017, 1, 15}, {10, 0, 27, 105598}}]

iex> HexWeb.Repo.query!("SELECT inserted_at FROM packages LIMIT 1", []).rows
[[{{2017, 1, 15}, {10, 0, 27, 105598}}]]

iex> {:ok, pid} = Postgrex.start_link(Application.get_env(:hex_web, HexWeb.Repo))
iex> Postgrex.query!(pid, "SELECT inserted_at FROM packages LIMIT 1", []).rows
[[~N[2017-01-15 10:00:27.105598]]]
```

**Comment by josevalim** [comment] 2017-01-20 13:47
The type API is only for casting external parameters. We can likely
generalize it for the use case above.

**Closed** 2017-08-07 11:05 UTC
Labels: Kind:Feature, Level:Advanced
