### ISSUE TITLE
~7 Second (31%) difference between Mix test and mix test --partitions in Ecto Heavy test suites

### ISSUE THREAD

**Issue by SophisticaSean** [elixir-ecto/ecto#3599] opened 2021-04-01 00:14 UTC
### Environment

* Elixir version (elixir -v): 1.11.3
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): Postgres:12-alpine (docker container)
* Ecto version (mix deps): 3.4.6
* Database adapter and version (mix deps): 3.4.6
* Operating system: Ubuntu 18.04
* Original issue: https://github.com/elixir-lang/elixir/issues/10853
### Current behavior

I was able to replicate this on this branch: https://github.com/SophisticaSean/elixir-async-testing/tree/testing-performance-issues

I know the tests are contrived but I didn't want to have to write a bunch of application logic to replicate my issue. It has something to do with tests that take a lot of Ecto time. The behavior I see is that on the `mix test` run it'll sometimes hang on the longer running Ecto heavy tests. No other tests report as complete when it hangs on these Ecto heavy tests. I believe this is why running parallel `mix test --partitions` runs is faster, they all separately hang on those heavy Ecto tests but since they're running in parallel they don't collectively slow each other down. We tested in this in the original issue with just a `:timer.sleep` implementation and adding `--max-cases` fixes the issue. This fix doesn't work for Ecto heavy tests though.

From this behavior I would hazard a guess that there's something wrong in the implementation of Ecto.Sandbox that's bottlenecking the tests.

My expectation would be that `mix test` would handle this case for me and have several other cpu threads working on other test files in tandem with the main `mix test` thread. So at any given time we should always have tests running and completing. 

Run tests script again (use `gdate` instead of `date` if you're on MacOs or Unix): 
```bash
function run_tests {
  unset pids
  start=$(date +%s.%N);
  for i in {1..$1}; do
    MIX_TEST_PARTITION=${i} mix test --partitions $1 &                
    pids[${i}]=$!
  done

  for pid in ${pids[*]}; do
    wait $pid
  done
  dur=$(echo "$(date +%s.%N) - $start" | bc);
  printf "Execution time: %.6f seconds\n" $dur
};
```

### Results
  - config/test.exs: `ecto_loop_count: 1000`
  - config/test.exs: `timer_sleep_loop_count: 10`
  - 32 Core Server ~2.6 ghz clock speed:
      - vanilla `time mix test --max-cases 384` average over 20 runs: 21.868 seconds
      - `run_tests 6` average over 20 runs: 17.3519 seconds
      - 31% speed difference.

### Expected behavior
  Vanilla `mix test` should be fastest, or very close to the hand parallelized version. Instead `run_tests 6` is 31% faster. This is also the case for my production test suite on a private github repo with ~750 tests and a lot of tests that interact with Ecto.

**Comment by josevalim** [comment] 2021-04-01 06:47
@SophisticaSean can you please see what happens when you increase your ecto_loop_count to 5000 or 10000? It takes 6.2 seconds for me to load the test files and I want to rule that partitioning is faster to load code rather than running it.

Alternatively, try this command: `mix test --exclude test --exclude doctest` and `MIX_TEST_PARTITION=... mix test --exclude test --exclude doctest --partitions 6` and see how faster it is.

**Comment by josevalim** [comment] 2021-04-01 07:00
Ok, I was unable to reproduce the issue on my machine. My guess is that we are hitting a bottleneck somewhere between 8 to 32 cores.

**Comment by SophisticaSean** [comment] 2021-04-01 07:10
I ran it on my 32 core server and I'm seeing this:

10000 ecto_loop_count test timeout

5000 ecto_loop_count:
   `time mix test --max-cases 384`: 54.130 seconds
   `run_tests 6`: 36.226630 seconds

**Comment by josevalim** [comment] 2021-04-01 07:43
> 5000 ecto_loop_count:

This is very interesting. I am *sure* we are spawning all of those tests concurrently but the tests running longer makes a strong impact on the overall results.

I have a couple more theories for us to test (in isolation):

1. What happens if you wrap the Ecto test in a Repo.checkout call?

2. What happens if instead of creating a user, you sleep on the database side of things?

> So 3.77 seconds for vanilla mix test and 1.914 seconds for partitioned mix test

To be clear, this is just one of the partitions, which means it load only part of the tests. Anyway, this is good enough to say the issue likely isn't with load times. Thanks!

**Comment by SophisticaSean** [comment] 2021-04-01 10:14
Results for 5000 Ecto loop count on 32 core machine:
checkout wrap inside loop
```elixir
  test "complex ecto user test" do    
    loop_count = Application.get_env(:async_testing, :ecto_loop_count)    
    Enum.each(1..loop_count, fn x ->    
      AsyncTesting.Repo.checkout(fn ->    
        email = Ecto.UUID.generate()    
        name = "Tim#{x}"    
        {:ok, user} = User.create(name, email)    
        assert user.name == name    
        assert user.email == email    
    
        user = User.get_by_email(email)    
        assert user.name == name    
        assert user.email == email    
      end)    
    end)    
  end    
```
- `mix test --max-cases 384`  58.667 seconds average over 3 runs
- `run_tests 6` 41.653 seconds average over 3 runs

Results for 5000 (`:timeout` increased to `60_000`) Ecto loop count on 32 core machine:
checkout wrap outside loop
```elixir
  test "complex ecto user test" do                                                               
    loop_count = Application.get_env(:async_testing, :ecto_loop_count)                           
                                                                                                 
    AsyncTesting.Repo.checkout(fn ->
      Enum.each(1..loop_count, fn x ->
        email = Ecto.UUID.generate()
        name = "Tim#{x}"
        {:ok, user} = User.create(name, email)
        assert user.name == name
        assert user.email == email

        user = User.get_by_email(email)
        assert user.name == name
        assert user.email == email
      end)
    end)
  end

```
- `mix test --max-cases 384`  47.863 seconds average over 3 runs
- `run_tests 6` 36.11 seconds average over 3 runs

**Comment by SophisticaSean** [comment] 2021-04-01 10:14
> What happens if instead of creating a user, you sleep on the database side of things?
I'm not sure what you mean by this, could you clarify?

**Comment by josevalim** [comment] 2021-04-01 10:21
@SophisticaSean ok, so the checking out of connections definitely play a role.

> I'm not sure what you mean by this, could you clarify?

Instead of User.create, do something like Repo.query!("SLEEP 0.1") or whatever is the SQL syntax for it.

Besides the above, can you please try to see what happens when using the regular pool instead of the ownership pool?

**Comment by SophisticaSean** [comment] 2021-04-01 20:14
Results for `AsyncTesting.Repo.query!("SELECT pg_sleep(#{duration});")` with duration of `0.01` and run_count of `5000`
```elixir
test "complex ecto database sleep test" do        
  loop_count = Application.get_env(:async_testing, :ecto_user_sleep_loop_count)                       
  duration = Application.get_env(:async_testing, :ecto_user_sleep_duration)    
  Enum.each(1..loop_count, fn _x ->                                                  
      assert :ok = User.sleep(duration)                                                               
  end)    
end
```
- `mix test --max-cases 384`  59.312 seconds average over 3 runs
- `run_tests 6` 58.866 seconds average over 3 runs

Results for `AsyncTesting.Repo.query!("SELECT pg_sleep(#{duration});")` with duration of `0.001` and run_count of `5000`
`same code as above`
- `mix test --max-cases 384`  41.736 seconds average over 3 runs
- `run_tests 6` 24.654  seconds average over 3 runs

**Comment by josevalim** [comment] 2021-04-01 20:21
Fantastic! Can you try with “SELECT 1”? It seems the issue is not the sleep but simply don’t the queries.

and then let’s try without the ownership pool. :)

**Comment by SophisticaSean** [comment] 2021-04-01 20:38
SELECT 1; results on Sandbox pool
Results for `AsyncTesting.Repo.query!("SELECT 1;;")` with run_count of `5000`
```elixir
  test "ecto database select_1 test" do
    loop_count = Application.get_env(:async_testing, :ecto_user_select_1_loop_count)
    Enum.each(1..loop_count, fn _x ->
        assert :ok = User.select_one()
    end)
  end
```
- `mix test --max-cases 384`  39.876 seconds average over 3 runs
- `run_tests 6` 20.462 seconds average over 3 runs

**Comment by SophisticaSean** [comment] 2021-04-01 20:43
SELECT 1; results on Default pool
Results for `AsyncTesting.Repo.query!("SELECT 1;;")` with run_count of `5000`
```elixir
  test "ecto database select_1 test" do
    loop_count = Application.get_env(:async_testing, :ecto_user_select_1_loop_count)
    Enum.each(1..loop_count, fn _x ->
        assert :ok = User.select_one()
    end)
  end
```
- `mix test --max-cases 384`  30.9 seconds average over 3 runs
- `run_tests 6` 18.969 seconds average over 3 runs

**Comment by josevalim** [comment] 2021-04-01 21:54
Ok, I have one last request. Can you wrap this loop in Repo.checkout(fn -> ... end) and let us know how it goes? Thank you! :heart:

**Comment by SophisticaSean** [comment] 2021-04-01 23:35
No worries, I'm happy to help. :)

SELECT 1; Repo.checkout wrap results on sandbox pool
Results for `AsyncTesting.Repo.query!("SELECT 1;;")` with run_count of `5000`
```elixir
  test "ecto database select_1 test" do
    loop_count = Application.get_env(:async_testing, :ecto_user_select_1_loop_count)
    AsyncTesting.Repo.checkout(fn ->
      Enum.each(1..loop_count, fn _x ->
          assert :ok = User.select_one()
      end)
    end)
  end
```
- `mix test --max-cases 384`  29.94 seconds average over 3 runs
- `run_tests 6` 17.32 seconds average over 3 runs

SELECT 1; Repo.checkout wrap results on default pool
Results for `AsyncTesting.Repo.query!("SELECT 1;;")` with run_count of `5000`
```code is same as above```
- `mix test --max-cases 384`  28.295 seconds average over 3 runs
- `run_tests 6` 15.795 seconds average over 3 runs

**Comment by josevalim** [comment] 2021-04-02 07:24
Ok, I have two last requests to test my theory.

First, can you run the same tests above (it can be whatever pool), but making sure that only the test above is executed? Something like this `mix test --only test:"test ecto database select_1 test"`.

Second, instead of using the connection pool, can you please start a Postgrex connection in the test and use it for the queries? It would be something like this:

    @config Repo.config()
    test "...." do
      {:ok, pid} = Postgrex.start_link(@config)
      enum do
        Postgres.query(pid, "SELECT 1")
      end
    end

And then you can try to run tests only with this test name again, so we remove any noise from other tests.

---

In any case, it is expected for the connection pool to be a bottleneck at some point, as it is a single process. These last tests is going to help confirm how much of it is contributed to by the pool or if there are other factors at play.

How would we solve this bottleneck in practice? If we were seeing this issue in production, I would address it by having `n` connection pools and picking one at random on every operation. This is actually fairly straight-forward and it can even be solved today by using the dynamic repo functionality.

However, we are talking about tests here and a big part of the issue here is confirmed to be the ownership pool. Once we moved from the ownership pool to the default pool, we got a 10 seconds improvement. But the ownership pool really has to be a global shared resource, with no partitioning, because it is meant to be accessed by any process that you might allow in the system. Its whole job is to share a connection between processes that want to collaborate together and at the moment I cannot think of anything we can do to speed this up - but I will keep throwing brain cycles at it.

**Comment by SophisticaSean** [comment] 2021-04-02 08:54
SELECT 1; Repo.checkout wrap sandbox pool this test only
Results for `AsyncTesting.Repo.query!("SELECT 1;;")` with run_count of `5000`
```elixir
  @tag :select_1
  test "ecto database select_1 test" do
    loop_count = Application.get_env(:async_testing, :ecto_user_select_1_loop_count)
    AsyncTesting.Repo.checkout(fn ->
      Enum.each(1..loop_count, fn _x ->
          assert :ok = User.select_one()
      end)
    end)
  end
```
- `mix test --only select_1 --max-cases 384`  30.223 seconds average over 3 runs
- `run_tests 6` (with --only select_1 filter) 17.104 seconds average over 3 runs

manual postgrex connection on default pool
```elixir
  @tag :manual_postgrex
  test "manual postgrex select_1 test" do
    loop_count = Application.get_env(:async_testing, :manual_postgrex_loop_count)
    {:ok, pid} = Postgrex.start_link(@config)
    Enum.each(1..loop_count, fn _x ->
      Postgrex.query!(pid, "SELECT 1;", [])
    end)
  end
```
- `mix test --only manual_postgrex --max-cases 384`  27.027 seconds average over 3 runs
- `run_tests 6` (with --only manual_postgrex filter) 14.424 seconds average over 3 runs

**Comment by SophisticaSean** [comment] 2021-04-02 08:56
So our whole test suite is `async: true` so I'm wondering if we should work on an option of disabling (or a readme/help/tutorial) to show people who are building async test suites how to reap a possible performance enhancement here. Right now Ecto funnels you through async: false and sandbox friendly testing so I think we need a path for the performance sensitive folks to squeeze out as much test performance as possible.

**Comment by SophisticaSean** [comment] 2021-04-02 08:57
I'm 100% fine leaving sandbox behind if its causing performance issues. I just need a path to do so.

**Comment by josevalim** [comment] 2021-04-02 09:36
I think there is a misunderstanding. The sandbox **is** the reason why you can use `async: true` because we need a mechanism to share a connection between processes. So Ecto is pushing you towards async: true and sandboxing. Without the sandbox, everything would be `async: false` and execution would be much, much slower.

To sum up, here are the numbers (with `--max-cases):

1. With ownership pool and max cases: 40s
2. With default pool and max cases: 30s
3. With direct connection and max cases: 27s

I think we can probably do something about 1 -> 2 and make the ownership pool (and testing) faster. I don't see, at the moment, much purpose on working on 2 -> 3.

---

However, the fact that a direct Postgrex connection still takes roughly the same time as the pool tells me the problem is elsewhere. Which is weird, because we have kind of ruled out the problem being elsewhere. Can we please try sleep once again? Maybe our mistake was using high sleeps. What happens if you do this:

```elixir
  @tag :sleep_1
  test "sleep 1" do
    loop_count = Application.get_env(:async_testing, :sleep_loop_count)
    Enum.each(1..loop_count, fn _x ->
      Process.sleep(1)
    end)
  end
```

**Comment by josevalim** [comment] 2021-04-02 10:07
@SophisticaSean can you please run the tests again with the ownership pool + select 1, but this time [using this branch for db_connection](https://github.com/elixir-ecto/db_connection/pull/238).

This should reduce the bottleneck by making all reads go through a ETS table, which should be the majority of hits.

**Comment by SophisticaSean** [comment] 2021-04-02 10:18
You're right, sorry about that I misunderstood what Sandbox was doing.

Here's the results for the `Process.sleep(1)` request and 10,000 loop_count:
- `mix test --only sleep_1 --max-cases 384`  24.15 seconds average over 3 runs
- `run_tests 6` (with --only sleep_1 filter) 23.183 seconds average over 3 runs

I'll work on the results for that other branch.

**Comment by SophisticaSean** [comment] 2021-04-02 10:28
SELECT 1; Repo.checkout wrap sandbox pool this test only
using this db_connection branch: https://github.com/elixir-ecto/db_connection/pull/238
Results for `AsyncTesting.Repo.query!("SELECT 1;")` with run_count of `5000`
```elixir
  @tag :select_1
  test "ecto database select_1 test" do
    loop_count = Application.get_env(:async_testing, :ecto_user_select_1_loop_count)
    AsyncTesting.Repo.checkout(fn ->
      Enum.each(1..loop_count, fn _x ->
          assert :ok = User.select_one()
      end)
    end)
  end
```
- `mix test --only select_1 --max-cases 384`  30.553 seconds average over 3 runs
- `run_tests 6` (with --only select_1 filter) 17.188 seconds average over 3 runs

**Comment by josevalim** [comment] 2021-04-02 10:29
@SophisticaSean sweet, we went from 40 to 30 for the ownership tests! Can you please try running that branch in your original repo that started all this and let us know how much it improve in practice?

**Comment by josevalim** [comment] 2021-04-02 10:33
> Here's the results for the Process.sleep(1) request and 10,000 loop_count:

Thank you! The Postgrex.start_link approach should be completely asynchronous... so I don't understand why it is running faster with partitions. It would be nice if we could now reproduce the slow down without Postgrex but it seems sleep is not enough to do it. :(

**Comment by SophisticaSean** [comment] 2021-04-02 10:48
Results of the test suite this issue originated from on the new db_connection branch:
 - `mix test --max-cases 384` 24.617 second average over 3 runs
 - `run_tests 6`  17.314 second average over 3 runs
 
 The test suite this is coming from is 762 tests and they're pretty evenly balanced between reads/writes so it looks like the change will help in the long run or for projects with many more ecto tests/ ecto reads. The averages seem to be about the same as when we started :(
 
I appreciate you taking the time to help me through this. I'm really eager to shave 7 seconds off our test run time if possible by alleviating this issue! :)

**Comment by josevalim** [comment] 2021-04-02 11:13
> Results of the test suite this issue originated from on the new db_connection branch:

So no improvements unfortunately. I don't think the difference is read/writes. Instead I think in our journey to simplification, we made it so the DBConnection ownership pool became the bottleneck, but that isn't the case in your app.

> I appreciate you taking the time to help me through this. I'm really eager to shave 7 seconds off our test run time if possible by alleviating this issue! :)

Yeah, unfortunately I just ran out of options. We ruled out the issue being Ecto and DBConnection and I am skeptical the issue will be Postgrex. So we either need to validate it being a Postgrex issue or try to reproduce without it.

**Comment by SophisticaSean** [comment] 2021-04-06 02:25
So how can I help? The example repo still showcases the very same discrepancy I'm seeing in my private repo. I don't think there should be a ~13 second difference between partition and no partition `mix test`.

**Comment by josevalim** [comment] 2021-04-06 06:21
We need to continue boiling it down. We were already able to bring it down to Postgrex, removing Ecto from the equation. So now we need to further change the example so we get closer to the bottleneck.

**Comment by josevalim** [comment] 2021-04-24 11:18
Any news here on a more minimal case? :) Thanks!

**Comment by josevalim** [comment] 2021-04-24 11:21
Oh, I had an idea. Can we focus on the Postgrex case, where you pass the options to start it manually without using Ecto at all? Then can we benchmark using a socket vs a hostname? Just the issue is something ip related.

**Comment by josevalim** [comment] 2021-05-07 15:00
This commit may also fix the issue: https://github.com/elixir-lang/elixir/commit/2eb03e4a314c0e6b986b4fb88af2df549e088288 - you will need Elixir master :)

**Comment by josevalim** [comment] 2021-05-18 06:27
Closing this for now, as it is surely not an Ecto issue. If you decide to take a further look at this, let's move this to Postgrex and continue from there. Thanks!

**Closed by josevalim** 2021-05-18 06:27 UTC
