### ISSUE TITLE
Preload not loading all data?

### ISSUE THREAD

**Issue by gmile** [elixir-ecto/ecto#2664] opened 2018-08-21 12:13 UTC
I'm facing Ecto behaviour I'm having hard time explaining to myself. Consider this example, which is also published on github as a standalone mix app – [`ecto_redundancy_issue`](https://github.com/gmile/ecto_redundancy_issue).

<details>
<summary>Schemas (hidden for brevity)</summary>

```elixir
defmodule Author do
  use Ecto.Schema

  schema "authors" do
    field :full_name, :string
    field :email, :string
  end
end

defmodule Comment do
  use Ecto.Schema

  schema "comments" do
    field :subject, :string
    field :content, :string
    field :post_id, :integer

    belongs_to :author, Author
  end
end

defmodule Post do
  use Ecto.Schema

  schema "posts" do
    field :title, :string
    field :body, :string

    has_many :comments, Comment
    has_many :commenters, through: [:comments, :author]
  end
end
```
</details>

Data:
```elixir
RedundancyRepo.insert_all("posts", [
  %{id: 1, title: "My title", body: "My body"}
])

RedundancyRepo.insert_all("authors", [
  %{id: 1, full_name: "Full name 1", email: "client1@server.com"},
  %{id: 2, full_name: "Full name 2", email: "client2@server.com"},
  %{id: 3, full_name: "Full name 3", email: "client3@server.com"}
])

RedundancyRepo.insert_all("comments", [
  %{id: 1, post_id: 1, author_id: 1, subject: "Subject 1", content: "Big content 1"},
  %{id: 2, post_id: 1, author_id: 2, subject: "Subject 2", content: "Big content 2"},
  %{id: 3, post_id: 1, author_id: 3, subject: "Subject 3", content: "Big content 3"},
  %{id: 4, post_id: 1, author_id: 1, subject: "Subject 4", content: "Big content 4"},
  %{id: 5, post_id: 1, author_id: 2, subject: "Subject 5", content: "Big content 5"},
  %{id: 6, post_id: 1, author_id: 3, subject: "Subject 6", content: "Big content 6"}
])
```

Test code:

```elixir
commenter_emails_query = from a in Author, select: struct(a, [:email])
posts_query = from p in Post, preload: [commenters: ^commenter_emails_query]

[post] = RedundancyRepo.all(posts_query)
post.commenters == Enum.map(post.comments, & &1.author) |> Enum.uniq |> Enum.sort # => false
```

I expect the final statement to be `true`. What am I missing?

### Environment

* Elixir version: Elixir 1.7.2 (compiled with Erlang/OTP 21)
* Database and version: PostgreSQL 10.5
* Ecto version (mix deps): master branch, specifically 63d075d66201819e37d6774f155a487ace583855
* Database adapter and version (mix deps): 0.13.5
* Operating system: macOS

### Current behavior

Preload is not loading all authors.

### Expected behavior

Preload loads all authors.

**Comment by josevalim** [comment] 2018-08-21 12:33
Can you please post your schema declarations?

**Comment by gmile** [comment] 2018-08-21 12:34
@josevalim it's in the body of the issue. Click "Schemas (hidden for brevity)". Here it is once again:

```elixir
defmodule Author do
  use Ecto.Schema

  schema "authors" do
    field :full_name, :string
    field :email, :string
  end
end

defmodule Comment do
  use Ecto.Schema

  schema "comments" do
    field :subject, :string
    field :content, :string
    field :post_id, :integer

    belongs_to :author, Author
  end
end

defmodule Post do
  use Ecto.Schema

  schema "posts" do
    field :title, :string
    field :body, :string

    has_many :comments, Comment
    has_many :commenters, through: [:comments, :author]
  end
end
```

**Comment by josevalim** [comment] 2018-08-21 12:37
Oh, thanks! I believe this is a duplicate of #2534. You can confirm it by looking at the SQL queries in logs.

**Comment by gmile** [comment] 2018-08-21 12:46
@josevalim got it. Thanks for looking into this! Closing.

**Comment by josevalim** [comment] 2018-08-21 12:56
Thanks @gmile for the detailed issue and the app to reproduce it. I am back at the computer now so I can look at things more closely but I decided to ask you upfront in case it was something simpler. :)

**Comment by josevalim** [comment] 2018-08-21 13:04
@gmile oh, your issue is a separate one. Ecto computes the uniqueness by ID and, since you remove the IDs from the association, we consider all of them to be equal. Maybe we should raise if the ID is nil?

**Closed** 2018-08-21 13:13 UTC
