### ISSUE TITLE
Generating a migration in a custom directory (i.e manual_migrations) creates the wrong module namespace

### ISSUE THREAD

**Issue by itayadler** [elixir-ecto/ecto#3521] opened 2020-12-22 08:59 UTC
### Environment

* Elixir 1.11.2 (compiled with Erlang/OTP 23)
* PostgreSQL 12
*    {:phoenix_ecto, "~> 4.1"},
      {:ecto_sql, "~> 3.4"},
*    {:postgrex, ">= 0.0.0"}
* Operating system: Mac OS Catalina 10.15.6

### Current behavior

Running:
`mix ecto.gen.migration --migrations-path=priv/repo/manual_migrations update_users`
creates the migration file in the `priv/repo/manual_migrations` path with the module namespace:
```
defmodule Api.Repo.Migrations.UpdateUsers do
...
end
```

### Expected behavior
```
defmodule Api.Repo.ManualMigrations.UpdateUsers do
...
end
```

Otherwise the migration won't work during a release.

**Comment by BlueHotDog** [comment] 2020-12-22 09:01
Just to add some context here, the source of the confusion is due to the Dashbit article explaining this practice but not mentioning this issue. regardless would be nice to solve this for everyone ever trying to do this

**Comment by wojtekmach** [comment] 2020-12-22 09:12
Why would the migration not work during the release? Can you paste an error you're getting? The module name doesn't have to follow the filename.

**Comment by itayadler** [comment] 2020-12-22 09:15
I didn't get an error, it just ran the migrations successfully and didn't end up running the manual migration file. It started working when I renamed the module namespace from Migrations to ManualMigrations.
I did what the dashbit article suggested, and ran the manual migrations during release with the command:
```/bin/app_name eval Api.Release.migrate_manual```

**Comment by itayadler** [comment] 2020-12-22 09:15
also it works in development, just not in release

**Comment by josevalim** [comment] 2020-12-22 09:23
Can you please share the code of your `Api.Release` module? The module name should have no impact on the migration.

**Comment by itayadler** [comment] 2020-12-22 09:25
```
defmodule Api.Release do
  @moduledoc """
  note(itay): This module is used in our production build to run the migrations
  as recommended by https://hexdocs.pm/phoenix/releases.html#ecto-migrations-and-custom-commands

  To use change the run command of our docker image.
  Equivalent of `mix ecto.create` => ["/bin/api", "eval", "\"Api.Release.createdb\""]
  Equivalent of `mix ecto.migrate` => ["/bin/api", "eval", "\"Api.Release.migrate\""]
  """
  @app :api

  def createdb do
    IO.puts("Starting dependencies...")
    load_app()

    for repo <- repos() do
      :ok = ensure_repo_created(repo)
    end

    IO.puts("createdb task done!")
  end

  defp ensure_repo_created(repo) do
    IO.puts("create #{inspect(repo)} database if it doesn't exist")

    case repo.__adapter__.storage_up(repo.config) do
      :ok ->
        IO.puts("Repo created successfully")
        :ok

      {:error, :already_up} ->
        IO.puts("Error: Repo already up")
        :ok

      {:error, term} ->
        IO.puts("Error!")
        IO.puts(term)
        {:error, term}
    end
  end

  def migrate do
    IO.puts("Starting dependencies...")
    load_app()

    for repo <- repos() do
      IO.puts("Running schema migrations")
      IO.puts(repo)
      {:ok, _, _} = Ecto.Migrator.with_repo(repo, &Ecto.Migrator.run(&1, :up, all: true))
    end

    IO.puts("Migrate finished successfully")
  end

  def migrate_manual do
    IO.puts("Starting dependencies...")
    load_app()

    for repo <- repos() do
      path = priv_path_for(repo, "manual_migrations")
      IO.puts("Running manual migrations from path: #{path}")
      IO.puts(repo)
      {:ok, _, _} = Ecto.Migrator.with_repo(repo, &Ecto.Migrator.run(&1, path, :up, all: true))
    end

    IO.puts("Manual migration finished successfully")
  end

  def rollback(repo, version) do
    load_app()
    {:ok, _, _} = Ecto.Migrator.with_repo(repo, &Ecto.Migrator.run(&1, :down, to: version))
  end

  defp repos do
    Application.fetch_env!(@app, :ecto_repos)
  end

  defp load_app do
    Application.load(@app)
    Enum.each([:postgrex, :ecto, :ecto_sql], &Application.ensure_all_started/1)
  end

  defp priv_path_for(repo, filename) do
    app = Keyword.get(repo.config(), :otp_app)

    repo_underscore =
      repo
      |> Module.split()
      |> List.last()
      |> Macro.underscore()

    priv_dir = "#{:code.priv_dir(app)}"

    Path.join([priv_dir, repo_underscore, filename])
  end
end
```

**Comment by wojtekmach** [comment] 2020-12-22 09:48
I couldn't reproduce this locally. Could you create a sample app that reproduces your problem?

(For a second, I thought I _could_ reproduce this locally as I saw the migration didn't get executed but this is because I thought I properly rolled back my DB but I didn't. I called `mix ecto.rollback` but I should have: `mix ecto.rollback --migrations-path=priv/repo/manual_migrations`. Mentioning it just in case.)

Btw, you can replace:

```elixir
path = priv_path_for(repo, "manual_migrations")
```

with:

```elixir
path = Ecto.Migrator.migrations_path(repo, "manual_migrations")
```

**Comment by itayadler** [comment] 2020-12-22 09:50
sure, I'll do it later

**Comment by itayadler** [comment] 2020-12-22 10:22
also forgot to mention that I'm building the release using this Dockerfile:
```
FROM elixir:1.10.3-alpine AS build


# install build dependencies
RUN apk add --no-cache build-base npm git python


# prepare build dir
WORKDIR /app


# install hex + rebar
RUN mix local.hex --force && \
    mix local.rebar --force


# set build ENV
ENV MIX_ENV=prod


# install mix dependencies
COPY mix.exs mix.lock ./
COPY config config
RUN mix do deps.get, deps.compile




# build assets
# COPY assets/package.json assets/package-lock.json ./assets/
# RUN npm --prefix ./assets ci --progress=false --no-audit --loglevel=error


COPY priv priv
# COPY assets assets
# RUN npm run --prefix ./assets deploy
# RUN mix phx.digest


# compile and build release
COPY lib lib
# uncomment COPY if rel/ exists
# COPY rel rel
RUN mix do compile, release


# prepare release image
FROM alpine:3.9 AS app
RUN apk add --no-cache openssl ncurses-libs


WORKDIR /app


RUN chown nobody:nobody /app


USER nobody:nobody


COPY --from=build --chown=nobody:nobody /app/_build/prod/rel/api ./


ENV HOME=/app


CMD ["bin/api", "start"]
```

**Comment by josevalim** [comment] 2020-12-22 12:02
Cool! Please try to reproduce it outside of Docker just to rule out it being an issue with the docker setup. :)

**Comment by itayadler** [comment] 2020-12-22 12:04
Sorry I wasn't clear.
When I attempt to do a `mix release` locally, and run it it does seem to work.
However It doesn't seem to work with the Dockerfile I added here.

**Comment by wojtekmach** [comment] 2021-01-13 09:19
ping :) if you could create a sample project with instructions how to reproduce and put it e.g. on GitHub that would be appreciated.

**Comment by josevalim** [comment] 2021-01-19 08:36
Closing this for now. We will be glad to investigate if we have a complete reproduction script. Thank you!

**Closed by josevalim** 2021-01-19 08:36 UTC
Labels: Note:Needs more info
