### ISSUE TITLE
'No database selected' error during migration rollback with prefix specified

### ISSUE THREAD

**Issue by hogjosh** [elixir-ecto/ecto#2060] opened 2017-05-12 19:56 UTC
### Environment

* Elixir version: 1.4.1
* Database and version: MySQL 5.7.17
* Ecto version: 2.1.3
* Database adapter and version: mariaex 0.8.1
* Operating system: OSX

### Current behavior

I bumped into this when using the rollback mix task, but suspect it shows up under other conditions too.

```
$ MIX_ENV=test mix ecto.rollback  --repo TenantRepo.Repo1 --prefix sample_tenant_test
** (Mariaex.Error) (1046): No database selected
    (ecto) lib/ecto/adapters/sql.ex:440: Ecto.Adapters.SQL.execute_and_cache/7
    (ecto) lib/ecto/adapters/sql.ex:619: anonymous fn/3 in Ecto.Adapters.SQL.do_transaction/3
    (db_connection) lib/db_connection.ex:1276: DBConnection.transaction_run/4
    (db_connection) lib/db_connection.ex:1200: DBConnection.run_begin/3
    (db_connection) lib/db_connection.ex:791: DBConnection.transaction/3
    (ecto) lib/ecto/migrator.ex:246: anonymous fn/4 in Ecto.Migrator.migrate/4
    (elixir) lib/enum.ex:1229: Enum."-map/2-lists^map/1-0-"/2
    (ecto) lib/mix/tasks/ecto.rollback.ex:85: anonymous fn/4 in Mix.Tasks.Ecto.Rollback.run/2
```

We have a number of databases (with the same schema) and rely on prefixes extensively.  We do not set the :database param in config.exs.

The error occurs when the rollback tries to delete from the `schema_migrations` table, so it should have very little to do with the specific migration being rolled back.  To make matters worse, the rollback itself succeeds and the `schema_migrations` table ends up inconsistent with the database state.

I was able to trace the problem to a `Repo.delete_all/2` call
 [https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/migration/schema_migration.ex#L30](url)

If I replace this call to `Repo.delete_all/2` with independent get & delete calls, everything appears to work as intended.

I've also found that if I set the :database parameter in config.exs it appears to work as intended (but only for that particular database)

I chased this through the ecto code for a while, but I didn't find anywhere that the prefix was obviously being lost/ignored.  The sql generated appears valid:
```DELETE s0.* FROM `sample_tenant_test`.`schema_migrations` AS s0 WHERE (s0.`version` = ?)```

I suspect something is goofy with the prepared statement, but I'm far from a sql expert.

### Expected behavior

Migration rollback (and `Repo.delete_all/2`) work correctly with a prefix specified.

**Comment by josevalim** [comment] 2017-05-12 20:06
@hogjosh thank you for the report. Can you please provide a sample application that reproduces the error? It will be much easier for us to fix if we don't need to chase the exact scenarios that reproduce the issue. Thank you!

**Comment by hogjosh** [comment] 2017-05-12 21:10
Done and done!

https://github.com/hogjosh/ecto2060

It looks like ecto 2.1.4 added error information when there's a problem with `schema_migrations`, but I'm not sure it's helpful in this scenario.

Let me know if I can be of further help.

**Comment by josevalim** [comment] 2017-05-13 10:13
@hogjosh it seems to be an issue with MySQL:

$ mysql -u root
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 73
Server version: 5.7.11 Homebrew

Copyright (c) 2000, 2016, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

```
mysql> INSERT INTO `ecto_2060_dev`.`schema_migrations` (`version`,`inserted_at`) VALUES (1, "2017-05-05 10:10:10");
Query OK, 1 row affected (0.00 sec)

mysql> DELETE s0.* FROM `ecto_2060_dev`.`schema_migrations` AS s0 WHERE (s0.`version` = 20170512203256);
ERROR 1046 (3D000): No database selected
mysql>
```

For some reason it does not require a database for insert but it does not require one for deletions.

**Comment by hogjosh** [comment] 2017-05-13 10:50
@josevalim ah, I was running the sql from a graphical app, which was probably setting the database for me and is why it seemed to work there.

This appears to work:
```mysql> DELETE FROM `ecto_2060_dev`.`schema_migrations` WHERE (`version` = 20170512203256);
Query OK, 1 row affected (0.01 sec)```

There is definitely some "weirdness" when using aliases in deletes and specifying the database further complicates it...

**Comment by josevalim** [comment] 2017-05-13 10:56
@hogjosh if that query works, it definitely adds more weirdness. The issue is that none of this seems to be documented, so I am reluctant in putting all of the work required to emit other queries while there is no guarantee this will work for other MySQL versions or in the future.

If you don't want to have it connected to any of your prefixes, I would recommend setting up a dummy database for connections but not use it for anything else.

**Comment by josevalim** [comment] 2017-05-18 08:54
Closing this as we believe it is a MySQL issue and I don't believe we should change our query strategy specifically to handle MySQL weirdness. If you don't want to have it connected to any of your prefixes, I would recommend setting up a dummy database for connections but not use it for anything else. Thank you!

**Closed by josevalim** 2017-05-18 08:54 UTC
