### ISSUE TITLE
Running migration while testing failed in Ecto 3.0

### ISSUE THREAD

**Issue by melpon** [elixir-ecto/ecto#2784] opened 2018-11-01 12:38 UTC
Test code is here:

```elixir
defmodule MyAppTest do
  use ExUnit.Case

  defmodule Test do
    use Ecto.Schema

    schema "myapptest_test" do
      timestamps()
    end
  end

  defmodule TestMigration do
    use Ecto.Migration

    def change() do
      create table(:myapptest_test) do
        add(:inserted_at, :utc_datetime, null: false)
        add(:updated_at, :utc_datetime, null: false)
      end
    end
  end

  test "test" do
    Ecto.Adapters.SQL.Sandbox.unboxed_run(MyApp.Repo, fn ->
      Ecto.Adapters.SQL.Sandbox.mode(MyApp.Repo, {:shared, self()})
      Ecto.Migrator.up(MyApp.Repo, 100, TestMigration)
    end)
  end
end
```

And run `mix ecto.drop; mix ecto.create && mix test`. Result is here:

```
The database for MyApp.Repo has been dropped
The database for MyApp.Repo has been created
                           
21:14:22.282 [debug] QUERY OK source="schema_migrations" db=0.3ms
SELECT s0."version"::bigint FROM "schema_migrations" AS s0 FOR UPDATE []                 
                      
                      
  1) test test (MyAppTest)                  
     test/my_app_test.exs:23                
     ** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 978ms
     stacktrace:                                                        
       (db_connection) lib/db_connection.ex:766: DBConnection.transaction/3
       (ecto_sql) lib/ecto/migrator.ex:184: Ecto.Migrator.do_run_maybe_in_transaction/3
       (elixir) lib/task/supervised.ex:89: Task.Supervised.do_apply/2
       (elixir) lib/task/supervised.ex:38: Task.Supervised.reply/5
       (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

The test is passed in Ecto 2.2.11. So I think it is problem in Ecto 3.0.

I tested on Elixir 1.7.4 and macOS High Sierra and PostgreSQL 10.5.

Full project is here: https://github.com/melpon/ecto3-migration-issue

**Comment by josevalim** [comment] 2018-11-01 12:44
This is a duplicate of #2782. Unfortunately our migrations now need two database connections and the sandbox only ever uses one. For running migration in tests, I would recommend setting up a separate repository with the explicit purpose of testing those migrations.

**Closed by josevalim** 2018-11-01 12:44 UTC

**Comment by melpon** [comment] 2018-11-01 12:50
Thank you for your information! I will try to setup a separate repository.

**Comment by josevalim** [comment] 2018-11-01 12:54
Let me know if you have any questions! I think you can do something like this in your test_helper:

```elixir
options = Application.get_env(:my_app, MyApp.Repo)
defmodule MyApp.MigrationRepo do
  use Ecto.Repo, [adapter: Ecto.Adapters.Postgres, otp_app: :my_app] ++ options
end
MyApp.MigrationRepo.start_link
```
