### ISSUE TITLE
Ecto Query Planner cache fails on updated query

### ISSUE THREAD

**Issue by nhpip** [elixir-ecto/ecto#4452] opened 2024-07-18 00:21 UTC
### Elixir version

Elixir 1.16.0 (compiled with Erlang/OTP 26)

### Database and Version

PostgresSQL 11.17

### Ecto Versions

3.10.2

### Database Adapter and Versions (postgrex, myxql, etc)

postgrex 0.16.4

### Current behavior

I have a query, containing an alias, that contains a number of subqueries. The query is created as part of a management module, and depending on the request from the user we can select different sub-queries.

The issue is that the different combination of subqueries will eventually cause the following error:

```
Postgrex expected a boolean, got "bob". Please make sure the value you are passing matches the definition in your table or in your query or convert the value accordingly.
```
and the following stacktrace:
```
{Postgrex.DefaultTypes, :encode_params, 3, [file: ~c"lib/postgrex/type_module.ex", line: 947]},
{DBConnection.Query.Postgrex.Query, :encode, 3, [file: ~c"lib/postgrex/query.ex", line: 75]}, 
{DBConnection, :encode, 5, [file: ~c"lib/db_connection.ex", line: 1323]}, 
{DBConnection, :run_prepare_execute, 5, [file: ~c"lib/db_connection.ex", line: 1423]}, 
{DBConnection, :run, 6, [file: ~c"lib/db_connection.ex", line: 1527]}, 
{DBConnection, :parsed_prepare_execute, 5, [file: ~c"lib/db_connection.ex", line: 656]},
{DBConnection, :execute, 4, [file: ~c"lib/db_connection.ex", line: 709]}, 
{Ecto.Adapters.Postgres.Connection, :execute, 4, [file: ~c"lib/ecto/adapters/postgres/connection.ex", line: 102]}, {Ecto.Adapters.SQL, :execute!, 5, [file: ~c"lib/ecto/adapters/sql.ex", line: 858]}, 
{Ecto.Adapters.SQL, :execute, 6, [file: ~c"lib/ecto/adapters/sql.ex", line: 828]}, 
{Ecto.Repo.Queryable, :execute, 4, [file: ~c"lib/ecto/repo/queryable.ex", line: 229]}, 
{Ecto.Repo.Queryable, :all, 3, [file: ~c"lib/ecto/repo/queryable.ex", line: 19]}]
```

I can workaround the problem by creating a unique alias each time, but that's far from ideal.

The query is attached.
[ecto_query.txt](https://github.com/user-attachments/files/16276073/ecto_query.txt)

### Expected behavior

Allow the subqueries to be updated without an exception.

**Comment by josevalim** [comment] 2024-07-18 00:38
This is happening because we are building the wrong cache key. But to know what is missing, we would need a way to reproduce this issue. Can you please try simplifying the queries into a minimal case we can look into?

**Comment by greg-rychlewski** [comment] 2024-07-18 00:47
There was a fix for something that sounds similar to this last year https://github.com/elixir-ecto/ecto/pull/4242.

The fix was after 10.2 so it might be what you are experiencing.

**Comment by nhpip** [comment] 2024-07-18 00:49
Absolutely. I'm traveling the next few days so it may not be until after the weekend.

I also loved your interview on developer voices.

**Comment by josevalim** [comment] 2024-07-18 00:57
Oh yeah, double check if it is not fixed on 3.11. I thought 3.10.2 was latest :D

**Comment by nhpip** [comment] 2024-07-18 11:29
Hey, that seems to have fixed it. Thanks for your help, I'll let you know if it happens again.

Thanks for your help.

**Closed** 2024-07-18 11:41 UTC
Labels: Kind:Bug
