### ISSUE TITLE
The aggregation functions for expressions do not work correctly

### ISSUE THREAD

**Issue by salisbury-espinosa** [elixir-ecto/ecto#2070] opened 2017-05-21 19:14 UTC
### Environment

* Elixir 1.4.0
* PostgreSQL 9.4
* Ecto version 2.1
* Operating system: Ubuntu

### Current behavior

code
```elixir
(from b in __MODULE__,
      group_by: :currency,
      select: {b.currency, sum(b.amount - b.prev_amount)})
```

raise error:

> ** (Ecto.Query.CompileError) `b.amount() - b.prev_amount()` is not a valid query expression.

Now have to fix this:

```elixir
(from b in __MODULE__,
      group_by: :currency,
      select: {b.currency, sum(fragment("amount - prev_amount"))})
```

**Comment by josevalim** [comment] 2017-05-21 19:29
Duplicate of #1757.

**Closed by josevalim** 2017-05-21 19:29 UTC
