### ISSUE TITLE
Support fragments in Ecto subqueries

### ISSUE THREAD

**Issue by danielgracia** [elixir-ecto/ecto#1416] opened 2016-05-04 20:39 UTC
As of current release candidates of Ecto 2.0, when trying to use a fragment in a subquery, Ecto will bail out and raise a error, due to the lack of specific support for this situation. As pointed out by José in the mailing list though, it should be possible to implement, although not in time to the 2.0 release.

This should enable some more complex queries and powerful joins for SQL adapters, at least.
As an sidenote, the current situation probably should be better clarified in the module docs.

**Comment by danielgracia** [comment] 2016-05-04 20:39
For reference: https://groups.google.com/forum/#!topic/elixir-ecto/joRQF6VCxVg

**Comment by philipgiuliani** [comment] 2016-06-09 18:21
I just came into the same issue! How can i write this query in ecto currently:
```sql
SELECT * FROM (SELECT id, (hits / 1000.0) AS relevance FROM events) AS res WHERE res.relevance > 0.5
```

**Comment by josevalim** [comment] 2016-06-09 18:24
Do you need to write the query above as a subquery?

**Comment by philipgiuliani** [comment] 2016-06-09 18:27
Postgres doesnt allow me to access aliases in the where clause :( Im used to mysql where it was no problem...

Oh wait... I can actually do the calculation in the where, or?... I try :x

**Comment by josevalim** [comment] 2016-06-09 18:29
```elixir
Repo.all from e in Event, where: fragment("? / 1000", e.hits) > 0.5
```

**Comment by philipgiuliani** [comment] 2016-06-09 18:34
Ok of course, thanks @josevalim ... Seems that im used to much mysql magic. There i could use it in the HAVING clause. Awesome... 👍

**Comment by leobessa** [comment] 2016-07-14 21:55
I may have the same issue.
Let me know if I should open another issue or not.

I'm trying to convert the a SQL query with a function call into Ecto models:

```sql
select * from sql_function('edd1cfe1-b46e-4754-af24-690b6815934e');
```

It's not clear if this feature request will allow me to the following:
```elixir
from e in subquery(fragment("sql_function(?)", id))
```

Or the intended interface for that has no need for `subquery` like:
```elixir
from e in fragment("sql_function(?)", id)
```

In this latter case, my issue would be related to a sql function call only.

**Comment by michalmuskala** [comment] 2016-07-15 08:31
Supporting fragment as a query source is a separate issue.

The workaround for now (that does not work in every case) is to either use raw SQL or join on the function, since fragments are supported on joins.

**Comment by josevalim** [comment] 2016-09-08 07:25
Duplicate of #1616 (the error and the solution are the same).

**Closed by josevalim** 2016-09-08 07:25 UTC
Labels: Kind:Feature, Level:Advanced
