### ISSUE TITLE
(Ecto.QueryError) PostgreSQL requires a schema module when using selector "u0" but none was given.

### ISSUE THREAD

**Issue by olafura** [elixir-ecto/ecto#1592] opened 2016-07-20 13:29 UTC
Hi, I'm getting this error some of the time when running mix test. Either it should work or not work all of the time or have a better error message.

Here is my environment:
Erlang/OTP 19 [erts-8.0] [source] [64-bit] [smp:8:8] [async-threads:10] [kernel-poll:false]
Elixir 1.3.1
Ecto 2.0.2
Postgrex 0.11.2
Ubuntu 16.04

Error text:
     ** (Ecto.QueryError) PostgreSQL requires a schema module when using selector "u0" but none was given. Please specify a schema or specify exactly which fields from "u0" you desire in query:
     
     from u in "users",
       where: u.email == ^...,
       select: u

Stacktrace:
       (ecto) lib/ecto/adapters/postgres/connection.ex:834: Ecto.Adapters.Postgres.Connection.error!/2
       (ecto) lib/ecto/adapters/postgres/connection.ex:373: Ecto.Adapters.Postgres.Connection.expr/3
       (elixir) lib/enum.ex:1215: anonymous fn/4 in Enum.map_join/3
       (elixir) lib/enum.ex:1623: Enum."-reduce/3-lists^foldl/2-0-"/3
       (elixir) lib/enum.ex:1214: Enum.map_join/3
       (ecto) lib/ecto/adapters/postgres/connection.ex:203: Ecto.Adapters.Postgres.Connection.select/3
       (ecto) lib/ecto/adapters/postgres/connection.ex:101: Ecto.Adapters.Postgres.Connection.all/1
       (ecto) lib/ecto/adapters/postgres.ex:69: Ecto.Adapters.Postgres.prepare/2
       (ecto) lib/ecto/query/planner.ex:99: Ecto.Query.Planner.query_without_cache/3
       (ecto) lib/ecto/query/planner.ex:73: Ecto.Query.Planner.query_prepare/5
       (ecto) lib/ecto/query/planner.ex:48: Ecto.Query.Planner.query_with_cache/6
       (ecto) lib/ecto/repo/queryable.ex:119: Ecto.Repo.Queryable.execute/5
       (ecto) lib/ecto/repo/queryable.ex:40: Ecto.Repo.Queryable.all/4

**Comment by ericmj** [comment] 2016-07-20 14:12
You need to explicitly select fields. Since we have no schema we don't know which fields to select. Replace `select: u` with `select: {u.id, u.foo, ...}`.

Not sure if the error message can be improved.

**Comment by josevalim** [comment] 2016-07-20 14:20
@olafura if it happens only from time to time, can you provide a way to reproduce the error?

**Comment by josevalim** [comment] 2016-07-27 23:47
Closing this. Please let us know if you have more info.

**Closed by josevalim** 2016-07-27 23:47 UTC

**Comment by alex88** [comment] 2016-09-12 20:23
Having the same issue, but from a query without a schema, is there a way to specify a resulting schema for a query?

**Comment by olafura** [comment] 2016-09-13 13:35
Hi @alex88 I'll have to find time to try to replicate or look better into it, specially making the error message better. But I would follow what ericmj advised if you aren't selecting specific fields.

**Comment by alex88** [comment] 2016-09-13 15:00
@olafura in my case, the query is something like

```
select s2
from subquery(...) s1
left join lateral fragment(...) s2
```

The s2 table returns the whole fields of a schema (e.g. User), but there is no way to tell ecto that the resulting s2 is a User, so I have to:

```
select s2
from subquery(...) s1
left join lateral fragment(...) s2
inner join s3 in MyApp.User on s3.id == s2.id
```

which is bad for performance and useless if there would be a way to declare the resulting schema

**Comment by josevalim** [comment] 2016-09-13 18:33
See #1590 which will allow you to load the data later on. We could also support `struct(u, [:foo, :bar, :baz], MyModule)` but I'd prefer to get started with #1590 for now.

**Comment by alex88** [comment] 2016-09-13 19:20
@josevalim or even `struct(u, MyModule)` if there are all the columns since the module contains the column names
