### ISSUE TITLE
Ecto.Multi operations not always executed in order as added (Documentation Issue?)

### ISSUE THREAD

**Issue by begedin** [elixir-ecto/ecto#3578] opened 2021-03-08 14:06 UTC
### Environment

* Elixir version (elixir -v): 1.10.4
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): psql (PostgreSQL) 11.0
* Ecto version (mix deps): 

```
    {:ecto_sql, "~> 3.5", override: true},
    {:phoenix_ecto, "~> 4.2.1"},
```

* Database adapter and version (mix deps):  `{:postgrex, ">= 0.0.0"}`
* Operating system: Ubuntu 20.4

### Current behavior

Consider this basic example

```Elixir
    multi =
      Multi.new()
      |> Multi.run(:token, fn _, _ -> {:error, :invalid_token} end)
      |> Multi.insert(:user, %Ecto.Changeset{valid?: false})
      |> Multi.run(:invitations, fn _, _ -> {:ok, 1} end)
      |> Multi.run(:user_token, fn _, _ -> {:ok, "foo"} end)

    multi |> Multi.to_list() |> IO.inspect(label: "order")

    multi |> Repo.transaction() |> IO.inspect(label: "result")
```

Order will bi printed out as
```
order: [
  token: {:run, #Function<0.131121918/2 in Graphotate.Auth.RegisterUser.call/3>},
  user: {:insert,
   #Ecto.Changeset<action: :insert, changes: %{}, errors: [], data: nil,
    valid?: false>, []},
  invitations: {:run,
   #Function<1.131121918/2 in Graphotate.Auth.RegisterUser.call/3>},
  user_token: {:run,
   #Function<2.131121918/2 in Graphotate.Auth.RegisterUser.call/3>}
]
```

Result, however, is 

```
result: {:error, :user,
 #Ecto.Changeset<action: :insert, changes: %{}, errors: [], data: nil,
  valid?: false>, %{}}
```

### Expected behavior

Based on documentation, expected result would be 

```
result: {:error, :token, :invalid_token, %{}}
```

From the code, it seems like this is intentional. There is a precheck for all operations being valid, and one of the conditions is checking that all passed-in changesets are valid. This also makes sense in most cases as it saves a db trip.

However, the documentation does say

```
All operations will be executed in the order they were added.
```

So should this be updated, or is this behavior not intentional?

**Comment by josevalim** [comment] 2021-03-08 14:07
I will improve the docs, thank you!

**Comment by begedin** [comment] 2021-03-08 14:09
Much appreciated. I would be OK with submitting a PR myself to, if that is what you prefer, but I wanted to first check what the intent is.

**Comment by josevalim** [comment] 2021-03-08 14:10
Ah, we do mention this in the Changeset section: https://hexdocs.pm/ecto/Ecto.Multi.html#module-changesets

**Comment by josevalim** [comment] 2021-03-08 14:11
> I would be OK with submitting a PR myself to, if that is what you prefer, but I wanted to first check what the intent is.

Ah, a PR is welcome then! Yes, the behaviour is working as intended but perhaps the docs above can be clearer. :)

**Comment by josevalim** [comment] 2021-03-08 14:55
Closing in favor of the PR!

**Closed by josevalim** 2021-03-08 14:55 UTC
