### ISSUE TITLE
DBConnection Exception

### ISSUE THREAD

**Issue by satb** [elixir-ecto/ecto#1696] opened 2016-09-15 13:23 UTC
I am inserting a few records within a transaction. One of the records violates an exclusion constraint within postgres. Since I am using Repo.insert, I wasn't expecting an exception being thrown. However, an exception is thrown. Details below. Glad to share any more information.
```
** (exit) an exception was raised:
    ** (ArgumentError) cannot convert the given list to a string.

To be converted to a string, a list must contain only:

  * strings
  * integers representing Unicode codepoints
  * or a list containing one of these three elements

Please check the given list or call inspect/1 to get the list representation, got:

[{DBConnection, :fetch_info, 1, [file: 'lib/db_connection.ex', line: 1195]}, {DBConnection, :transaction_meter, 3, [file: 'lib/db_connection.ex', line: 1012]}, {DBConnection, :transaction, 3, [file: 'lib/db_connection.ex', line: 667]}, {Enum, :"-map/2-lists^map/1-0-", 2, [file: 'lib/enum.ex', line: 1184]}, {Enum, :"-map/2-lists^map/1-0-", 2, [file: 'lib/enum.ex', line: 1184]}, {Ecto.Adapters.SQL, :"-do_transaction/3-fun-0-", 3, [file: 'lib/ecto/adapters/sql.ex', line: 480]}, {DBConnection, :transaction_run, 4, [file: 'lib/db_connection.ex', line: 1063]}, {DBConnection, :run_begin, 3, [file: 'lib/db_connection.ex', line: 987]}, {DBConnection, :transaction, 3, [file: 'lib/db_connection.ex', line: 667]},....
```

**Comment by shhavel** [comment] 2016-09-15 13:29
@satb I think the error circumstances is not clear. Can you please follow [the issue template](https://github.com/elixir-ecto/ecto/blob/master/ISSUE_TEMPLATE.md)?

**Comment by fishcakez** [comment] 2016-09-15 13:50
`Repo.insert` can still raise for several reasons. In this situation there is a failed transaction, likely because of the failed constraint, and another query or transaction has been attempted. The postgres adapter can raise for this and other reasons: https://github.com/elixir-ecto/postgrex/blob/6289ee92479ed38190a121c984b9e478422dbd27/lib/postgrex.ex#L82-L84. Using a non-bang (!) function will only prevent database generated errors (e.g. `Postgrex.Error`) from being raised.

The cause of the error you posted is not clear because the stacktrace for the ArgumentError is missing. It would appear the `DBConnection.DConnectionError` is being rescued and the handling of that has a bug.

**Comment by fishcakez** [comment] 2016-09-15 13:57
As a quick note. DBConnection (and so Ecto SQL) transactions can be nested. If a nested transaction would be rolled back the parent transaction is marked as failed and all further attempts of using that transaction will raise. Once the top level transaction finishes, the whole transaction will be rolled back.

**Comment by josevalim** [comment] 2016-09-15 14:17
Closing until we get more info.

**Closed by josevalim** 2016-09-15 14:17 UTC
Labels: Note:Needs more info

**Comment by satb** [comment] 2016-09-15 17:32
This is the only stack trace that we see which I've already posted above. I am not doing any additional queries after the transaction is rolled back.

The code that is causing this looks like this:

inserts = Repo.transaction fn ->
  Enum.map(changesets, &Repo.insert/1)
end

I am doing some testing and intentionally violating the db constraint to see the behavior. If raising the exception is the expected behavior, then probably it is not an issue. If exceptions can still happen with Repo.insert, then it should probably be documented - https://hexdocs.pm/ecto/Ecto.Repo.html#c:insert/2. Happy to help.

Environment:
------------
Elixir version (elixir -v): 1.3.2
Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): Postgres 9.5.4
Ecto version (mix deps): 2.0.4
Database adapter and version (mix deps): postgrex 0.11.2
Operating system: Mac OSX

```
** (exit) an exception was raised:
    ** (DBConnection.ConnectionError) transaction rolling back
        (db_connection) lib/db_connection.ex:1195: DBConnection.fetch_info/1
        (db_connection) lib/db_connection.ex:1012: DBConnection.transaction_meter/3
        (db_connection) lib/db_connection.ex:667: DBConnection.transaction/3
        (elixir) lib/enum.ex:1184: Enum."-map/2-lists^map/1-0-"/2
        (elixir) lib/enum.ex:1184: Enum."-map/2-lists^map/1-0-"/2
        (ecto) lib/ecto/adapters/sql.ex:480: anonymous fn/3 in Ecto.Adapters.SQL.do_transaction/3
        (db_connection) lib/db_connection.ex:1063: DBConnection.transaction_run/4
        (db_connection) lib/db_connection.ex:987: DBConnection.run_begin/3
        (db_connection) lib/db_connection.ex:667: DBConnection.transaction/3
```

**Comment by fishcakez** [comment] 2016-09-15 17:56
@satb I thought the exact exception (`ArgumentError` about formatting(?) the `DBConnection.ConnectionError`) you posted in the initial comment was coming from `Ecto`, that did not have it's stacktrace attached. My comment was about the exception you just posted, sorry for the mixup there.

When inserting the changeset a nested transaction is used. This nested transaction is rolled back if the insert query fails and this marks the top level transaction to rollback. As the error is ignored, the next insert will raise (if there is one) because the top level transaction is marked to roll back and this will prevent starting a nested transaction for the next insert.

The transaction docs explain this behaviour better than I have here.  We should probably point to those docs for functions that get an implicit transaction.

**Comment by fishcakez** [comment] 2016-09-15 18:04
> I am not doing any additional queries after the transaction is rolled back

The stacktrace shows that an insert is happening after the transaction is rolled back. A transaction is opened, `Enum.map` anonymous fun is called, a nested transaction is attempted to be started but the transaction is rolling back.

**Comment by satb** [comment] 2016-09-15 18:18
Ah! Thanks. That makes sense now. So Enum.map(changesets, &Repo.insert/1) inside a transaction could probably fail with this exception unless we also check within the function for Enum.map whether each insert succeeded. If one of those inserts fails, we wouldn't want to continue on with the other inserts (or, alternatively, wait for the exception itself to handle everything)

**Comment by josevalim** [comment] 2016-09-15 18:35
@satb check out `Ecto.Multi`. It is *exactly* what you need!
