### ISSUE TITLE
Ecto Crashing (Connection Error) - Create & Migrate Tenant Schema

### ISSUE THREAD

**Issue by brandonparsons** [elixir-ecto/ecto#1875] opened 2016-12-27 06:17 UTC
### Environment

* Elixir version (elixir -v): `1.3.2`
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): `PostgreSQL 9.4.1`
* Ecto version (mix deps): `2.1.1`
* Database adapter and version (mix deps): `postgrex 0.13.0`
* Operating system: `Mac`

### Issue

I am trying to use Postgres schemas and Ecto's query prefix functionality to run a multi-tenant database setup.

When an "Operator" is created, I obviously need to create the associated schema, and migrate it. I'm getting Ecto DB connection errors during this operation **the first time that I run it**. If I re-run the code a second time, it succeeds...

Here is the relevant code:

```elixir
  defp creation_multi(changeset) do
    Multi.new
    |> Multi.insert(:operator, changeset)
    |> Multi.run(:create_schema, &create_schema/1)
    |> Multi.run(:migrate_schema, &migrate_schema/1)
  end

  defp create_schema(%{operator: operator}) do
    schema_name = "tenant_#{operator.slug}"
    result = SQL.query(Repo, ~s{CREATE SCHEMA \"#{schema_name}\";})
    case result do
      {:ok, _result} -> {:ok, schema_name}
      {:error, reason} -> {:error, reason}
    end
  end

  defp migrate_schema(%{operator: operator}) do
    schema_name = "tenant_#{operator.slug}"
    result = Mix.Task.run "ecto.migrate", ["--quiet", "--prefix", schema_name]
    case result do
      :ok -> {:ok, schema_name}
      :noop -> {:ok, schema_name}
      otherwise -> {:error, otherwise}
    end
  end
```

This code fails the first time it is run, as per below:

```
[debug] QUERY OK db=0.2ms
begin []
[debug] QUERY OK db=2.7ms
INSERT INTO "public"."operators" (fields....) VALUES (data....)
[debug] QUERY OK db=0.6ms
CREATE SCHEMA "tenant_test-operator"; []
** (DBConnection.ConnectionError) tcp send: closed
[debug] QUERY ERROR db=2.3ms
commit []
    (db_connection) lib/db_connection.ex:793: DBConnection.transaction/3
             (ecto) lib/ecto/repo/queryable.ex:21: Ecto.Repo.Queryable.transaction/4
        (kidgenius) lib/myapp/actions/operators.ex:33: Myapp.Actions.Operators.create_with_schema/1
        (kidgenius) lib/myapp/domain/operator.ex:120: Myapp.Domain.Operator.insert_stub_and_schema/1
```

Now when I run the exact same snippet of code that creates the Operator again:

```
[debug] QUERY OK db=0.3ms
begin []
[debug] QUERY OK db=1.9ms
INSERT INTO "public"."operators" (fields....) VALUES (data....)
[debug] QUERY OK db=0.7ms
CREATE SCHEMA "tenant_test-operator" []
[debug] QUERY OK db=0.5ms
commit []
%Myapp.Domain.Operator{__meta__: #Ecto.Schema.Metadata<:loaded, "public", "operators">,
 more_data....}
```

Any help would be appreciated!

**Comment by brandonparsons** [comment] 2016-12-27 06:35
Note that I have already tried adjusting the timeouts (that I know of) in the Ecto config:

- `pool_timeout: 60_000`
- `timeout: 60_000`

**Comment by brandonparsons** [comment] 2016-12-27 06:58
P.P.S. This appears to work if I do **not** do this inside an `Ecto.Multi`.

i.e. Maybe it has something to do with me trying to run the mix task inside a transaction?

**Comment by josevalim** [comment] 2016-12-27 09:58
That may be it. Try starting the transaction manually or a hand rolled pg session and see what happens. ALso, it is very likely you don't want to call `Mix.Task.run "ecto.migrate"`. First of all, it will run only once as Mix protects against multiple invocations. You probably want to build something on top of Ecto.Migrate instead. :)

**Comment by fishcakez** [comment] 2016-12-27 10:25
It looks like there is a bug in Postgrex or DBConnection because commit should not be executed if the connection has disconnected in such a repeatable way. It would be interesting to see if we could reproduce this in a simpler example.

Is there a log message saying `Postgrex.Protocol` disconnected? If so could you show it? The log output from the failure should not occur so you might have made an error redacting things. If that is the actual output then we have split up errors in the logs, which means logs could interleave and be hard to read. If there is no log output it suggests that postgresql is closing the connection and we might be able to produce a better error in Postgrex (postgres has sent a fatal error and is no longer reading from the socket).

**Comment by brandonparsons** [comment] 2016-12-27 14:33
@fishcakez The log that I pasted in above was everything I got back in my console. Is there a different way I can try to grab this?

**Comment by brandonparsons** [comment] 2016-12-27 14:39
@josevalim I got the following working using `Ecto.Migrator`:

```elixir
  defp creation_multi(changeset) do
    Multi.new
    |> Multi.insert(:operator, changeset)
    |> Multi.run(:schema, &handle_schema/1)
  end

  def handle_schema(%{operator: operator}) do
    schema_name = "tenant_#{operator.slug}"

    # Create the tenant's schema
    {:ok, _result} = SQL.query(Repo, "CREATE SCHEMA \"#{schema_name}\"", [])

    # Migrate the schema
    result = Ecto.Migrator.run(
      Repo,
      Path.join(Mix.Ecto.build_repo_priv(Repo), "migrations"),
      :up,
      prefix: schema_name, all: true, log: false
    )
    case result do
      [_version] -> {:ok, nil}
      otherwise -> {:error, otherwise}
    end
  end
```

I'm happy to try other things if you want to do something else with this error.

Two related questions for you or @fishcakez if you don't mind.....

1. Is there a way to get `Ecto.Migrator` to run against the default path so I don't have to use `Path.join(Mix.Ecto.build_repo_priv(Repo), "migrations")`? I thought I read somewhere that `Mix` calls in app code could cause issues with releases in the future. (I'm new to Elixir).
2. I'd prefer to not interpolate the schema name right into the `CREATE SCHEMA` query in Ecto, but I seem to be having trouble getting the SQL escaping feature to work.  i.e. `Ecto.Adapters.SQL.query(Repo, "CREATE SCHEMA $1", ["test-operator"])` doesn't work.

**Comment by josevalim** [comment] 2016-12-27 14:54
@fishcakez oh, because they were using  the ecto.migrate task, it restarts the application, which was causing all connections to shutdown most likely?

**Comment by josevalim** [comment] 2016-12-27 14:55
1. `Mix.Ecto` is private API so don't call anything in it. You can build the path in the same way the function you were calling does.

2. You will have to escape it (which you were not doing) and interpolate it directly. Postgres does not allow schemas to be passed as parameters.

**Closed by josevalim** 2016-12-27 14:55 UTC

**Comment by fishcakez** [comment] 2016-12-27 15:00
@brandonparsons exactly as jose says. You may want to look at docs for `Application.app_dir/2`.

@josevalim I thought we only restarted apps that weren't already started? Similarly we didn't stop the repo if it was already started. However if it works how you say then it would make perfect sense.

Why is the banner split from the stacktrace in the output?

**Comment by brandonparsons** [comment] 2016-12-27 19:53
Is there a function in `Ecto` that will SQL sanitize strings? I couldn't find one by poking around or googling. :)

**Comment by fishcakez** [comment] 2016-12-28 11:15
@brandonparsons there isn't.

**Comment by brandonparsons** [comment] 2016-12-28 14:17
@fishcakez Thanks for confirming. Still finding my way around Ecto.

I did figure out that I could create a regular Postgres dynamic SQL function that takes a name as an argument and creates the schema. That way I can take advantage of Postgres' native string escaping (`%I`/`%l`).

Threw this in a migration then calling the function from my code.
