### ISSUE TITLE
Provide fragment's type information with Ecto.Query.API.type

### ISSUE THREAD

**Issue by lacrosse** [elixir-ecto/ecto#1872] opened 2016-12-22 18:42 UTC
### Precheck

This was suspected to work [at least once](https://groups.google.com/d/msg/phoenix-talk/WcqJRDYBf5k/0pKQ90YjFwAJ) before.

### Environment

* Elixir version: 1.3.4
* Database and version: PostgreSQL 9.6.1
* Ecto version: 2.1.1
* Database adapter and version: postgrex 0.12.1

### Current behavior

This example shows how `type` behaves with `fragment` as its `interpolated_value`:

```elixir
Ecto.Query.from(u in User, select: u.inserted_at, limit: 1) |> Repo.one
# ~N[2016-12-22 13:37:28.000000]
Ecto.Query.from(u in User, select: fragment("?", u.inserted_at), limit: 1) |> Repo.one
# {{2016, 12, 22}, {13, 37, 28, 0}}
Ecto.Query.from(u in User, select: type(fragment("?", u.inserted_at), :naive_datetime), limit: 1) |> Repo.one
# ** (Ecto.Query.CompileError) `type(fragment("?", u.inserted_at()), :naive_datetime)` is not a valid query expression.
```

### Desired behavior

```elixir
Ecto.Query.from(u in User, select: type(fragment("?", u.inserted_at), :naive_datetime), limit: 1) |> Repo.one
# ~N[2016-12-22 13:37:28.000000]
```

**Comment by josevalim** [comment] 2016-12-22 18:58
It did not work back then but we may try to make it work now.

**Comment by spscream** [comment] 2017-01-24 21:45
I'm using fragments with json functions in one of queries and it is not possible to cast types.  Will be great to have a possibility to cast type on fragment variables, this is one of queries, which returns not expected result(report.inserted_at isn't casted to :utc_datetime):
```
    from e in query,
      left_join: report in ChatEventReport, on: e.sync_id == report.sync_id,
      group_by: [e.keys, e.payload, e.sync_id, e.group_chat_id, e.event_type, e.inserted_at],
      select: %{keys: e.keys,
                payload: e.payload,
                sync_id: e.sync_id,
                group_chat_id: e.group_chat_id,
                event_type: e.event_type,
                inserted_at: e.inserted_at,
                received_by: fragment("array_agg(json_build_object('huid', ?, 'reported_at', ?))
                                      FILTER (WHERE ? = 'message_received_report')",
                                      report.user_huid, report.inserted_at, report.report_type),
                read_by: fragment("array_agg(json_build_object('huid', ?, 'reported_at', ?))
                                  FILTER (WHERE ? = 'message_mark_read_report')",
                                  report.user_huid, report.inserted_at, report.report_type)}
```

**Comment by josevalim** [comment] 2017-02-04 19:17
Duplicate of #1920.

**Closed by josevalim** 2017-02-04 19:17 UTC
Labels: Kind:Feature, Level:Advanced

**Comment by bigcurl** [comment] 2017-03-19 06:12
Has this been done or was it just closed? What is the syntax if it was added? Example above still fail.

**Comment by josevalim** [comment] 2017-03-19 08:03
It was closed as duplicate of another issue and you can see the other issue
is still open. :)
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*
