### ISSUE TITLE
Problem to join with different postgresql schemas

### ISSUE THREAD

**Issue by yconselvan** [elixir-ecto/ecto#2369] opened 2018-01-10 22:33 UTC
### Environment

* Elixir version: Elixir 1.4.4  ( Erlang/OTP 20 [erts-9.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false] )
* Database and version: PostgreSQL 9.5.10
* Ecto version: ecto 2.1.4
* Database adapter and version: postgrex 0.13.2
* Operating system: Linux 3e30dded55e2 4.9.0-5-amd64 #1 SMP Debian 4.9.65-3+deb9u2

### Current behavior

We are getting problem to make join with tables in different postgresql schemas

With a simple join with two tables 

revenue_metrics = (from r in Ppa.RevenueMetric,
      join: university in Ppa.University, on: university.id == r.university_id,

in the revenue_metrics.ex model definition there is a 

  @schema_prefix "ppa"

and in the university.ex model definition there is 

  @schema_prefix "qb"

>>> the sql generated looks like
SELECT ... FROM "ppa"."revenue_metrics" AS r0 INNER JOIN "ppa"."universities"

### Expected behavior

>>> the sql generated looks like
SELECT ... FROM "ppa"."revenue_metrics" AS r0 INNER JOIN "qb"."universities"

**Comment by josevalim** [comment] 2018-01-10 22:54
This is documented behaviour: the schema prefix apply only for the from. You cannot go through multiple prefix in the same query.

**Comment by OvermindDL1** [comment] 2018-01-10 22:57
Yeah this is a *huge* limitation of Ecto that I've run into rather constantly @yconselvan and you can drop in to either raw SQL (losing Ecto's type checking and conversions and such) or, as you are using PostgreSQL, you can just create some View tables if you have access (which I, sadly, did not in some cases...).  I'm not really sure of any other workarounds currently...

**Comment by yconselvan** [comment] 2018-01-10 23:32
I can drop into becoming a hater of ecto too ..

**Comment by yconselvan** [comment] 2018-01-10 23:38
@josevalim you don't need to support this schema prefix if you can't go through multiple prefix in the same query. If I can't join another schema why to have schemas?

**Comment by isaacsanders** [comment] 2018-01-29 18:31
@josevalim We have this problem, too. What would need to happen to implement the expected behavior, and would it be accepted if contributed?

**Comment by josevalim** [comment] 2018-01-29 18:51
Ecto 3.0 will likely make this possible, since we will allow `:join` to accept multiple keywords. Reopening so we can further talk about it.

**Comment by josevalim** [comment] 2018-01-29 19:00
@isaacsanders if there is someone willing to work on it, please let us know. We are looking for developers willing to continuously work on Ecto and this can be a great starting point! I think we can start with some simple steps:

1. Change the `from`  field in Ecto.Query to store a new FromExpr struct that will have the fields file, line, source and prefix. The prefix field will still exist in Ecto.Query

2. Change JoinExpr to have a prefix field and start computing such prefix from the schema in Ecto.Query.Planner

3. Change the database adapters (MySQL and Postgres in our case) to read both from and join prefix, falling back to the query prefix only if the from/join prefixes are nil

Those can all be sent as separate pull requests to ease review.

**Comment by isaacsanders** [comment] 2018-01-29 19:34
@josevalim Something I have never quite understood is: Why do FromExpr & JoinExpr need the prefix field? Can it not read the value from the Ecto schema that it is from-ing & joining from?

**Comment by josevalim** [comment] 2018-01-29 19:39
@isaacsanders because we want to get the data as digested as possible to the adapters and not have them be querying the schema. Otherwise we would be coupling the adapters directly to the schema.

**Comment by OvermindDL1** [comment] 2018-01-29 19:39
@isaacsanders Plus what if you are using schema-less queries?

**Comment by isaacsanders** [comment] 2018-01-29 19:47
@josevalim The prefix isn't a top-level part of the FromExpr or the JoinExpr, though. The level of abstraction that they belong to is the one where the table name or view name belongs to, IMO.

@OvermindDL1 I think a syntax/argument structure could be developed for that.

**Comment by josevalim** [comment] 2018-01-29 19:58
> The level of abstraction that they belong to is the one where the table name or view name belongs to

Then we are simply talking about keeping it alongside the `:source` field in FromExpr/JoinExpr or having them as a separate field. We would probably have gone with the former if we had prefixes since the beginning but they were added in Ecto 2.0 and changing how sources were specified would cause a good amount of rework in adapters.

**Comment by josevalim** [comment] 2018-02-09 08:06
Any news?

**Comment by isaacsanders** [comment] 2018-02-09 13:15
I will take a look at it this weekend

**Comment by isaacsanders** [comment] 2018-02-10 16:58
@josevalim Should I store the schema? or should that be as a pair with the source?

**Comment by josevalim** [comment] 2018-02-10 17:30
The Postgres Schema, which we call prefix, should be stored as a separate
field in JoinExpr as changing the source would require large changes in the
codebase and in adapters.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by isaacsanders** [comment] 2018-02-10 17:44
The Ecto schema.

**Comment by josevalim** [comment] 2018-02-10 17:50
The Ecto Schema is already stored in the source as a tuple. We don’t want
to change it for the same reason: it will break our code and adapters too.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by isaacsanders** [comment] 2018-02-10 18:14
I was just checking.

**Comment by josevalim** [comment] 2018-02-10 18:20
No problem!
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by isaacsanders** [comment] 2018-02-10 22:49
How should I preserve the functionality to prefix whole queries?

As I see it, the assumed use case for the schema prefix (multi-tenant type applications) & the one that is used in the original issue (grouping of data) are in conflict with each other. Any guidance on how to approach this conflict?

**Comment by josevalim** [comment] 2018-02-10 23:18
Yes, if a join doesn’t have a prefix nor one was set in its schema, it will
fallback to the query one.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by isaacsanders** [comment] 2018-02-11 00:22
So I shouldn't remove the query prefix?

**Comment by josevalim** [comment] 2018-02-11 08:42
No, we shouldn't. That would be backwards incompatible too.

**Comment by michalmuskala** [comment] 2018-05-23 16:58
With the new way query expressions are composed, this one should be easier to implement.

**Comment by josevalim** [comment] 2018-05-30 11:40
Closing in favor of #2572.

**Closed by josevalim** 2018-05-30 11:40 UTC
Labels: Kind:Feature, Level:Intermediate
