### ISSUE TITLE
Calling Exception.message on an InvalidChangesetError crashes

### ISSUE THREAD

**Issue by hfjallemark** [elixir-ecto/ecto#3426] opened 2020-09-29 08:09 UTC
### Environment

* Elixir version (elixir -v): 1.10.2
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 12.4
* Ecto version (mix deps): 3.4.6
* Database adapter and version (mix deps): postgrex: 0.15.6
* Operating system: macOSCatalina 10.15.6

### Current behavior

I'm trying to call `Exception.message`  on an `InvalidChangesetError` but it crashes:

```
** (Ecto.InvalidChangesetError) got FunctionClauseError with message "no function clause matching in Ecto.Changeset.traverse_errors/2" while retrieving Exception.message/1 for %Ecto.InvalidChangesetError{action: :insert, changeset: :rollback}
```

From what I can see https://github.com/elixir-ecto/ecto/blob/v3.4.6/lib/ecto/changeset.ex#L2869 requires a `Changeset` struct as the first param but in this case it looks like the changeset it set to :rollback for some reason. I am running some things in a transaction here so suspect it has something to do with that.

### Expected behavior

It should not crash when calling `Exception.message` on this type of `InvalidChangesetError`.

**Comment by josevalim** [comment] 2020-09-29 08:28
Can you please provide a complete case that reproduces the error? It is most likely that the error is in the `:rollback` appearing suddently, rather than in InvalidChangesetError. thanks!

**Comment by hfjallemark** [comment] 2020-09-29 09:11
I haven't been able to reproduce it locally. I tried manually rolling back within the transaction as well as forcing an invalid changeset without success.

Here's the code:

```elixir
Repo.transaction(fn ->
  existing_article = Repo.get_by(Article, site_id: site_id, url: url)

  article =
    if existing_article do
      update_article(existing_article, downloaded_article, site)
    else
      insert_article(url, downloaded_article, site)
    end

  if site.organization_id == nil do
    check_duplicates(article)

    unless article.content == nil do
      AnotherJob.new(%{article_id: article.id})
      |> Oban.insert!()
    end
  end
end)
```

And here's the stack trace:

```
(Ecto.InvalidChangesetError) got FunctionClauseError with message "no function clause matching in Ecto.Changeset.traverse_errors/2" while retrieving Exception.message/1 for %Ecto.InvalidChangesetError{action: :insert, changeset: :rollback}
    (oban 2.1.0) lib/oban.ex:259: Oban.insert!/2
    (ecto_sql 3.4.5) lib/ecto/adapters/sql.ex:875: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
    (db_connection 2.2.2) lib/db_connection.ex:1427: DBConnection.run_transaction/4
    (my_app 0.1.0) lib/my_app/downloader.ex:26: MyApp.Downloader.perform/1
    (oban 2.1.0) lib/oban/queue/executor.ex:161: Oban.Queue.Executor.perform_inline/1
    (oban 2.1.0) lib/oban/queue/executor.ex:149: Oban.Queue.Executor.perform_inline/1
    (oban 2.1.0) lib/oban/queue/executor.ex:69: Oban.Queue.Executor.call/1
    (elixir 1.10.2) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
```

Looks like the error may originate from Oban, but I've searched its codebase without finding any trace of any `:rollback` value. @sorentwo any ideas?

**Comment by sorentwo** [comment] 2020-10-23 14:02
Pardon my slow reply, I didn't receive a notification when @hfjallemark mentioned me. After taking a look in `Oban.insert!/2` I can see that the error is coming from https://github.com/sorentwo/oban/blob/master/lib/oban.ex#L288. The [documented return](https://hexdocs.pm/ecto/3.5.3/Ecto.Repo.html#c:insert/2) for `Repo.insert/2` is:

```elixir
{:ok, Ecto.Schema.t()} | {:error, Ecto.Changeset.t()}
```

Though it seems that calling insert within a transaction that times out [can also return](https://hexdocs.pm/ecto/3.5.3/Ecto.Repo.html#c:transaction/2) `{:error, any()}`, and in this particular case the `any()` is `:rollback`.

My instinct is to use a stricter match like `{:error, %Changeset{} = changeset}` and add another case to wrap those other error values. However, I don't see an appropriate Ecto exception to wrap with. Using a generic `RuntimeError` doesn't seem right. Any suggestions?

**Comment by josevalim** [comment] 2020-10-24 20:51
Which scenario is it not returning a changeset? I need to understand it better in order to say the best way forward. :)

**Comment by sorentwo** [comment] 2020-10-26 12:51
I believe the scenario arises from a timeout based `DBConnection.ConnectionError`. However, I'm having a hard time recreating the scenario locally. The following snippet does _not_ recreate the scenario the way I hoped it would, though I think it illustrates how the scenario could happen:

```elixir
Repo.transaction(fn ->
  Repo.query("select pg_sleep(10)")

  with {:error, changeset} <- Repo.insert(%Oban.Job{worker: "Foo", args: %{}}) do
    raise Ecto.InvalidChangesetError, action: :insert, changeset: changeset
  end
end)
```

**Comment by josevalim** [comment] 2020-10-26 16:24
Oh, I see the issue. [The result you are matching on](https://github.com/sorentwo/oban/blob/master/lib/oban/query.ex#L45) is the result of a transaction, which you also reproduced in the snippet above, so you indeed need to consider it may be returning a rollback value. You can raise a runtimeerror or even have a specific oban error, it probably doesn't matter much , as no one should be rescuing it, so go for clarity.

I think we can close this one though, as it is not an ecto issue. :)

**Closed by josevalim** 2020-10-26 16:24 UTC
Labels: Note:Needs more info

**Comment by hfjallemark** [comment] 2020-10-26 16:58
Yep, thanks guys!

**Comment by sorentwo** [comment] 2020-10-26 17:18
@josevalim Nicely spotted. Thanks for digging in one more level.

**Comment by tfwright** [comment] 2021-11-28 23:03
I just ran into this as well, although I am not myself using a transaction, just `insert!`, the implementation of which itself looks like it assumes the error value will always be a changeset:

https://github.com/elixir-ecto/ecto/blob/b69d1085cfd491a859f1be36463afcf4838e4891/lib/ecto/repo/schema.ex#L265-L276

It seems like the case statement there needs a clause to specifically handle a value of :rollback and return a generic error message in that case?

**Comment by hfjallemark** [comment] 2021-11-29 04:45
@tfwright Are you running this inside a `Repo.transaction`?

**Comment by tfwright** [comment] 2021-11-29 17:24
No, I'm not. II think Ecto itself wraps insert statements in a transaction though, and in some cases rolls them back:

https://github.com/elixir-ecto/ecto/blob/b69d1085cfd491a859f1be36463afcf4838e4891/lib/ecto/repo/schema.ex#L315-L342

https://github.com/elixir-ecto/ecto/blob/b69d1085cfd491a859f1be36463afcf4838e4891/lib/ecto/repo/schema.ex#L987

**Comment by v0idpwn** [comment] 2021-11-30 07:27
@tfwright can you provide something that reproduces this issue?

**Comment by tfwright** [comment] 2021-11-30 16:18
@v0idpwn unfortunately no I'm not sure exactly what the cause might be. It might be timeout related as @sorentwo suggested above. If what he says is accurate though about insert not always returning a changeset as the error value, then it would seem the code I linked above from `insert!` has the same problem Oban did and needs the same fix.

**Comment by v0idpwn** [comment] 2021-12-01 07:12
Even though do_insert may wrap in a transaction, I can't see it returning anything other than what the spec specifies. In all situations that I see, `adapter.rollback/1` receives a changeset, thus returning `{:error, changeset}`.

As a casual test, I patched and found that this never happens inside Ecto test/pg integration test suite. So I'm inclined towards believing it's not possible. If you can get a snippet that reproduces it we may be able to see if i

**Comment by v0idpwn** [comment] 2021-12-01 07:19
I'm working on an integration test that reproduces the issue.

**Comment by v0idpwn** [comment] 2021-12-01 10:42
@tfwright which isolation level are you using? Any chance its something different than `read comitted`?

**Comment by tfwright** [comment] 2021-12-01 16:13
I don't believe so. I haven't changed any of the default settings around that. It's possible there's something on the db level. I'm using postgres and unfortunately I don't have full control over the prod database. But I have access and can check on a config if that's helpful.

**Comment by josevalim** [comment] 2021-12-02 09:28
This line:

     {:error, changeset} -> adapter.rollback(adapter_meta, changeset) 

Should not be an issue because it makes the transaction error with value `{:error, changeset}`. My bet would be a changeset callback (prepare_changes) maybe rolling back? If you can provide a stacktrace, it might help. :) For now, I will add guards to those clauses.

**Comment by v0idpwn** [comment] 2021-12-02 14:07
I managed to reproduce the issue with the following diff:

```diff
index 005bbde5..e457588e 100644
--- a/integration_test/cases/repo.exs
+++ b/integration_test/cases/repo.exs
@@ -107,6 +107,24 @@ defmodule Ecto.Integration.RepoTest do
     assert post.inserted_at
   end
 
+  test "reproducing bug #3426" do
+    shared_uuid = Ecto.UUID.generate()
+    p1 = %Post{uuid: shared_uuid} |> Ecto.Changeset.change() |> Ecto.Changeset.unique_constraint(:uuid)
+    p2 = %Post{uuid: Ecto.UUID.generate()} |> Ecto.Changeset.change() |> Ecto.Changeset.unique_constraint(:uuid)
+    p3 = %Post{uuid: shared_uuid} |> Ecto.Changeset.change() |> Ecto.Changeset.unique_constraint(:uuid)
+
+    user =
+      %User{}
+      |> Ecto.Changeset.change()
+      |> Ecto.Changeset.put_assoc(:posts, [p1, p3, p2])
+      
+
+    TestRepo.transaction(fn ->
+      {:error, %Ecto.Changeset{}} = TestRepo.insert(user)
+    end)
+    |> IO.inspect()
+  end
+
```

**Comment by v0idpwn** [comment] 2021-12-02 14:10
I thought I had managed to reproduce this for a second :')

I think it can only happen if the transaction enters an invalid state. This can be achieved through breaking constraints (handled, unless proven wrong), maybe by transaction isolation level?

**Comment by tfwright** [comment] 2021-12-02 15:15
Here is the trace I am seeing. 

```
Ecto.InvalidChangesetError: got FunctionClauseError with message "no function clause matching in Ecto.Changeset.traverse_errors/2" while retrieving Exception.message/1 for %Ecto.InvalidChangesetError{action: :update, changeset: :rollback}
  File "lib/ecto/repo/schema.ex", line 287, in Ecto.Repo.Schema.update!/4
```
The rest are internal to my application, but the offending line is a call to `Repo.update!` not, as I said above, in a transaction or Multi. The code block looks like this:

```
    record
    |> Repo.preload(:assoc)
    |> Changeset.change()
    |> Changeset.put_assoc(:assoc, assoc_lis)
    |> Repo.update!(prefix: prefix)
```

It fails only very rarely.
