### ISSUE TITLE
Assigning same `DateTime` value to schema causes to mark field as changed

### ISSUE THREAD

**Issue by asiniy** [elixir-ecto/ecto#1935] opened 2017-02-04 07:04 UTC
### Environment

* Elixir version (elixir -v): 1.4.1
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 9.5.5
* Ecto version (mix deps): 2.1.3
* Database adapter and version (mix deps): 0.13.0
* Operating system: Ubuntu

### Current behavior

Assigning same `DateTime` value causes to mark field as changed. IE

``` elixir
defmodule User do
  use MyApp.Web, :model

  schema "users" do
    # bla-bla-bla
    field :last_sign_in_at, :utc_datetime
  end
end
```

``` elixir
user = Repo.get(User, 1)
dt = user.last_sign_in_at # => #<DateTime(2016-01-25T03:00:00.000000Z Etc/UTC)>
user |> cast(%{ last_sign_in_at: "2016-01-25T03:00:00Z" }, [:last_sign_in_at]) # => #Ecto.Changeset<action: nil,
 changes: %{last_sign_in_at: #<DateTime(2016-01-25T03:00:00Z Etc/UTC)>},
 errors: [], data: #User<>, valid?: true>

Absolutely the same date, but casted from string, marks changeset as having change!
```

### Expected behavior

It shouldn't be marked as change (the value is the same actually)

**Comment by josevalim** [comment] 2017-02-04 08:34
They are different because they have different microsecond precision. So they are not the exact same datetime. You can see that in the printed format.

However, it is up to debate if we should ignore this case or not.

**Comment by michalmuskala** [comment] 2017-02-04 08:54
I think we need to address it in some way, given always we get max precision from database and min precision from parsing.

**Comment by asiniy** [comment] 2017-02-04 11:54
@josevalim this is the same datetime, because 1.0 and 1 are equal in the real world, not a type system. When you are saying 1 meter you assume 1 meter not 1 meter 2 centimeters. IMHO

**Comment by josevalim** [comment] 2017-02-04 12:09
@asiniy no, they are not equal. Let's say we are going to meet on the day 23rd. If I don't give you more precise information, you could potentially wait the whole day for me to arrive. However, if I give you more precise information, such as a period or a specific hour, then you have a better idea of when we are going to meet. Note I used a day instead of an hour in the example because in speech "meeting at 12h" is implicitly implied to be 12h00.

When we are talking about units, `5.0` is very different from `5.000`. The former would have error between `4.95<->5.05` and the other between `4.9995` and `5.0005`. Check out the section about [quantification on wikipedia](https://en.wikipedia.org/wiki/Accuracy_and_precision) for more information.

Still, a possible answer is "we don't care about such precision here" and that would be a valid answer. I just want to point out that **they are not the same datetime** although you could consider them to be the same for certain purposes.

**Comment by josevalim** [comment] 2017-02-04 19:24
One option is to fix during casting and ensure it has the same precision. However, it doesn't fix the cases described in #1869 when directly inserting datetime values in the struct.

**Comment by josevalim** [comment] 2017-03-30 14:30
Here is another issue being caused by the lack of precision: https://github.com/phoenixframework/phoenix/issues/2222

**Comment by josevalim** [comment] 2017-05-18 08:47
Closing in favor of #2018.

**Closed by josevalim** 2017-05-18 08:47 UTC
Labels: Kind:Chore, Level:Intermediate
