### ISSUE TITLE
Upsert doesn't read the existing binary id if available

### ISSUE THREAD

**Issue by alex88** [elixir-ecto/ecto#1966] opened 2017-02-27 04:39 UTC
### Environment

* Elixir version (elixir -v): 1.4.2
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 9.6.2
* Ecto version (mix deps): 2.1.3
* Database adapter and version (mix deps): postgrex 0.13.0
* Operating system: OSX

### Current behavior

I'm trying to do an upsert for a row using:

```
App.Repo.insert!(%App.City{identifier: "holtsville", name: "Holtsville", state_id: "NY"}, on_conflict: [set: [identifier: "holtsville", name: "Holtsville", state_id: "NY"]], conflict_target: [:identifier, :state_id])
```

Table has an unique constrain on `identifier` and `state_id`, id is binary id.
Ecto runs this query:

```
INSERT INTO "cities" AS c0 ("identifier","name","state_id","id") VALUES ('holtsville','Holtsville','NY','0cfd4c5c-f946-4786-8803-71927053e37c')
ON CONFLICT ("identifier","state_id")
DO UPDATE SET identifier = 'holtsville', name = 'Holtsville', state_id = 'NY'
```

### Expected behavior

The returned struct has the ID of the row already in the database if exists.

### Problem
It seems that since ecto generates the binary id, it doesn't use `RETURNING id` to be able to set the `id` into the struct if the row already exists in the database

**Comment by josevalim** [comment] 2017-02-27 09:12
None of the columns will be returned automatically. What happens if you pass `returning: [:id]` to your insert?

**Comment by alex88** [comment] 2017-02-27 13:31
Same, tried

```
App.Repo.insert!(%App.City{identifier: "holtsville", name: "Holtsville", state_id: "NY"}, on_conflict: [set: [identifier: "holtsville", name: "Holtsville", state_id: "NY"]], conflict_target: [:identifier, :state_id], returning: [:id})
```

and the query doesn't show `RETURNING` inside

**Comment by josevalim** [comment] 2017-02-27 13:44
@alex88 yes, sorry, returning doesn't work for insert, only insert_all. This should be fixed if you set read_after_writes: when defining the binary_id.

    @primary_key {:id, :binary_id, autogenerate: true, read_after_writes: true}

That's what the `:id` key does by default.

**Comment by alex88** [comment] 2017-02-27 13:57
@josevalim shouldn't that be configurable by operation? So it runs only when we run an upsert with server side autogenerated ids? Since it's useful only when doing upserts in this case

**Comment by josevalim** [comment] 2017-02-27 14:08
Yes, it could be done by operation but that API does not exist today. If someone is willing to the work, please do send a PR. :)

**Comment by alex88** [comment] 2017-02-27 14:14
Ok, in case I find the time, what API are you talking about? Adding `returning` to insert or?

**Comment by josevalim** [comment] 2017-02-27 14:28
Add `:returning` to `insert`, yes. :)

**Comment by alex88** [comment] 2017-03-01 01:52
@josevalim so, I was looking at the PR,

```
@primary_key {:id, :binary_id, autogenerate: true, read_after_writes: true}
```

this doesn't work, it throws `cannot mark the same field as autogenerate and read_after_writes`

anyway, I think I did some progress changing

```
return = schema.__schema__(:read_after_writes)
```

to

```
return = case opts[:returning] do
      true                    -> schema.__schema__(:fields)
      list when is_list(list) -> list
      _                       -> schema.__schema__(:read_after_writes)
    end
```

this way it has the same api as `insert_all` either list, true or false.
This actually changes the query, however I miss the part where the schema picks up the data from the database, any hint?

**Comment by michalmuskala** [comment] 2017-03-01 07:15
How does it work with regular ids? Did they also present a similar issue, or they "just worked"?

If they "just worked" we shouldn't require users to add additional options to insert - switching between integer ids and binary ids should be seamless.

**Comment by josevalim** [comment] 2017-03-01 09:01
@michalmuskala I agree although MySQL may be an issue (well, it is an issue regardless since it never returns the ID on upserts).

@alex88 I will reopen this because now I think we should make your original scenario work.

**Comment by michalmuskala** [comment] 2017-03-01 10:50
@josevalim then I think we'd need to either raise or set the id to `nil` in case of MySQL. But keeping the wrong value can be very confusing.

**Comment by alex88** [comment] 2017-03-01 14:15
@michalmuskala with regular ids, I've just run some tests with a table like

```
create table(:models) do
  add :name, :string
  timestamps()
end
create unique_index(:models, [:name])
```

```
iex(2)> TestApp.Repo.insert(%TestApp.SomeModel{name: "foo"})
INSERT INTO "models" ("name","inserted_at","updated_at") VALUES ($1,$2,$3) RETURNING "id" ["foo", {{2017, 3, 1}, {14, 9, 22, 604237}}, {{2017, 3, 1}, {14, 9, 22, 607839}}]

iex(4)> TestApp.Repo.insert(%TestApp.SomeModel{name: "bar"}, on_conflict: :replace_all, conflict_target: [:name])
INSERT INTO "models" ("name","inserted_at","updated_at") VALUES ($1,$2,$3) ON CONFLICT ("name") DO UPDATE SET "name" = EXCLUDED."name","inserted_at" = EXCLUDED."inserted_at","updated_at" = EXCLUDED."updated_at" RETURNING "id" ["bar", {{2017, 3, 1}, {14, 13, 5, 400989}}, {{2017, 3, 1}, {14, 13, 5, 400995}}]
```

but this works because regular ids are generated by the database and this line https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/repo/schema.ex#L641 adds the id key to the list of return values

**Comment by alex88** [comment] 2017-03-14 05:11
Merged in a1746d5afd487ba862e834c1a280081996656196

**Comment by seantanly** [comment] 2017-05-26 02:46
@alex88 Thanks for fixing this. :)

@josevalim 
I have encountered this problem (Postgresql 9.6.3, Ecto 2.1.4) and took a while to figure out what's going on, trying to determine whether I'm using the new upsert `on_conflict` support wrongly or it's an issue with Ecto...

To prevent others using auto-generated binary_id/uuid from encountering the same problem with the current release >.<, will the fix be back ported to the current 2.1 branch? Or at least should there be a warning emitted when primary key is auto-generated binary_id and used with `on_conflict`? Or a update on Docs warning about not mixing the two? 

Going forward, I'm guessing it's related to https://github.com/elixir-ecto/ecto/issues/2025, there is a need for the docs to highlight the idiosyncrasies of using `@primary_key {:id, :binary_id, autogenerate: true}` with the upsert support. Currently using upsert this way always returns a wrong `id` value beyond the first query, which is way more confusing than returning simply `nil`, as highlighted by @michalmuskala .

**Comment by josevalim** [comment] 2017-05-26 08:09
@seantanly can you please send a pull request that documents those idiosyncrasies? Then we can see how much work is in backporting the doc changes and the :returning option to 2.1. In any case, sorry for the issues, and documenting them can be a great help to avoid others from running into it in the future!

**Comment by seantanly** [comment] 2017-05-26 16:32
@josevalim no worries, I'm just trying to help with feedback. I'm not sure whether I fully understand to the idiosyncrasies to document them.

I tried playing around with Ecto 2.1.4 branch but couldn't figure out how to change the `primary_key_type` such that https://github.com/elixir-ecto/ecto/issues/2025 can be captured as a test case, since it conflicts with the example given at https://hexdocs.pm/ecto/Ecto.Repo.html#c:insert/2-upserts 
which states `assert ignored.id == nil`. 

Although the test at
https://github.com/elixir-ecto/ecto/blob/v2.1/integration_test/cases/repo.exs#L1087
tests for this, and running `MIX_ENV=pg mix test` passes, manually creating a test project with `@primary_key {:id, :binary_id, autogenerate: true}` reproduced the issue.
https://github.com/seantanly/ecto_upsert_issue

As for the current issue of binary_id not being returned, I cherry-picked @alex88 's commit above for branch v2.1 and the tests passed. 

With the commit, it will still require users who are using binary_id primary key to add `returning: true` to obtain the expected behavior.

**Comment by seantanly** [comment] 2017-05-26 16:33
To simply things, I'm wondering whether Ecto.insert with `on_conflict` should simply return all fields read after write from DB by default. For performance optimization, the user can use `returning: [interested fields list]`, or `returning: false` in which ecto should return `nil` to prevent ambiguity. Issue #2025 related Doc above seems to imply `ignored.id == nil` can be used as conflict detection which I don't think Ecto is doing.

This should make the usage easier to understand and less user error prone, compared to currently needing to know `id` is sometimes returned and not all fields are updated.

**Comment by josevalim** [comment] 2017-05-26 16:38
> I'm wondering whether Ecto.insert with on_conflict should simply return all fields read after write from DB by default.

Isn't this the case though? We should always have read_after_writes in insert, regardless if on_conflict is used. The returning option is just for the case read_after_writes is not specified.

**Comment by seantanly** [comment] 2017-05-26 17:15
> Isn't this the case though? We should always have read_after_writes in insert, regardless if on_conflict is used. The returning option is just for the case read_after_writes is not specified.

Sorry, I wasn't clear on that point, confusing it with read_after_writes fields. What I meant was reading back all fields defined in schema from DB by default. The reason is, the naive user might be expecting the returned struct to accurately reflect what's on the DB, after all it's an {:ok, struct} tuple. Without doing this, the behavior deviates from the normal insert whereby the user can be assured the returned struct is accurate.

**Comment by josevalim** [comment] 2017-05-26 17:19
The problem with any of those changes is that it is not guaranteed to work across all DBs. We do our best to not be constrained by the weakest DB and that's why we support a lot of PG specific behaviour, but our default schema operation should be as compatible as possible.

**Comment by seantanly** [comment] 2017-05-26 18:05
The weakest DB here I assume is MySQL. To be still inline with the normal insert, perhaps it will be worthwhile to construct a separate select query for the MySQL adaptor to read back the values, with the docs stating for MySQL it's not a single atomic query. 

Alternatively, enforce `returning` must be specified when `on_conflict` is used. This forces the user to take notice and choose how to handle it. 

In using the `returning` option, PG supports any of the schema fields, while MySQL only supports the primary key. And the returned struct should only populate the stipulated fields.

**Comment by josevalim** [comment] 2017-05-26 18:53
> Alternatively, enforce returning must be specified when on_conflict is used. This forces the user to take notice and choose how to handle it.

Then for the cases where the user does not care (such as fire and forget), they are know being forced to specify something they did not need.

I think the best is to:

1. document that, if you want the data to be back `on_conflict`, you need to use `:returning` or specify the relevant fields as `:read_for_writes`

2. update the current upsert docs to mention that the primary key will only be returned if it is managed by the database

**Comment by seantanly** [comment] 2017-05-27 00:00
> Then for the cases where the user does not care (such as fire and forget), they are know being forced to specify something they did not need.
In this case, I think It is necessary for them to explicitly put `returning: false`. 

IMO being explicit is important because the returned result deviates from the normal insert. The code should be self-describing on what is the expected result, to prevent errors and have easier maintenance.

**Comment by josevalim** [comment] 2017-05-27 08:21
> IMO being explicit here is important because the returned result deviates from the normal insert.

That's not true since normal insert does not return data from the database and you can have stale data in memory even for regular inserts.

>  The code should be self-describing on what is the expected result, to prevent errors and have easier maintenance.

That can also be used as an argument for `returning: true`, so it is explicit that data is being fetched back.

Because the default behaviour of `returning: true` cannot work on MySQL and we won't make it perform two operations - which we never do anywhere, we cannot simply flip the default for returning.

**Closed** 2017-05-27 08:31 UTC
Labels: Kind:Bug, Level:Intermediate, Note:Discussion

**Comment by seantanly** [comment] 2017-05-27 09:20
> That's not true since normal insert does not return data from the database and you can have stale data in memory even for regular inserts.

The difference happens when we're taking into account autogenerated values, e.g. autogenerated binary_id, or even timestamps(). Without specifying return, currently the returned result will contain these auto-generated fields with newly generated values which is different from what's on the DB. Whereas a conventional insert doesn't have this problem because a successful insert means these generated values gets applied into the DB, thus the returned result is reflective of the DB value, at least at a certain pt in time. In the case of on_conflict with the returned newly generated auto-gen values were never applied at all, and that catches people off-guard.

Because of this discrepancy, user need to understand the difference that auto-generated values is causing, and use e.g. `returning: [:id, :inserted_at, :updated_at]` if they want to ensure the returned fields in result is correct at least at a point in time. Without adding that and naively using those returned fields will result in errors.

**Comment by josevalim** [comment] 2017-05-27 09:28
But isn't that true for any field in the struct in upsert? If you have a success as a result of upsert, any field except the conflict target is potentially out of date. The autogenerated fields do not add nor remove to that.

**Comment by josevalim** [comment] 2017-05-27 09:29
> Because of this discrepancy, user need to understand the difference that auto-generated values is causing, and use e.g. returning: [:id, :inserted_at, :updated_at]

To further clarify, this is not specific to autogenerated fields. Any field is potentially out of date.

**Comment by josevalim** [comment] 2017-05-27 09:33
In any case, we could look into not applying the auto generated fields but at the moment it is unclear if the database will return us enough information to make this distinction.

**Comment by josevalim** [comment] 2017-05-27 09:34
I have opened #2079. Thanks for the discussion!

**Comment by seantanly** [comment] 2017-05-27 09:39
>To further clarify, this is not specific to autogenerated fields. Any field is potentially out of date.

Which is the reason I proposed to return `{:ok, nil}` by default unless `returning` is defined to avoid any confusion in the validity of fields being returned. I guess the reason not to for now is to also support `read_after_writes` in upsert by default even when `returning` is not specified.

Yup, if Ecto autogenerated fields isn't included in the resulting fields unless being read back via `returning` or `read_after_writes` that will help avoid a lot of the confusion.

**Comment by seantanly** [comment] 2017-05-27 09:47
> In any case, we could look into not applying the auto generated fields but at the moment it is unclear if the database will return us enough information to make this distinction.

Why not simply not apply the auto-generated fields in the result unless specified in `returning` or `read_after_writes`? I don't think the user should differ their code logic based on Ecto being able to automatically detect a conflict happening, by virtue of auto-generated fields being present or not in the resulting fields.

**Comment by josevalim** [comment] 2017-05-27 09:52
@seantanly that would break all of uses of insert existing today. The point of autogeneration is exactly to take care of those before sending it to the database.

**Comment by josevalim** [comment] 2017-05-27 09:52
Plus read_after_writes is orthogonal to autogeneration because you can still have the field autogenerated but a TRIGGER in the database changes it, requiring you to use read_after_writes to get the value back.

**Comment by seantanly** [comment] 2017-05-27 10:00
> that would break all of uses of insert existing today. The point of autogeneration is exactly to take care of those before sending it to the database.

I meant not applying auto-generated fields in the result of upsert, not touching the normal inserts.

**Comment by josevalim** [comment] 2017-05-27 10:16
That's what the new issue is about. But it is unclear if we can get this
information from the database.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by seantanly** [comment] 2017-05-27 12:44
> In any case, we could look into not applying the auto generated fields but at the moment it is unclear if the database will return us enough information to make this distinction.
> I have opened #2079. Thanks for the discussion!
> That's what the new issue is about. But it is unclear if we can get this
information from the database.

In spirt of above, but not relying on detecting for conflict, I have created a commit that doesn't return any auto generated fields when `on_conflict` is not raised. I'll let the code do the talking instead to avoid any ambiguity.

https://github.com/seantanly/ecto/commit/9814efcfcf7cc6141533eb7c7d426a9bec2cd3c3

I can't run the test for `MIX_ENV=mysql mix test`, errors propped out complaining about `Access denied for user 'randomuser'@'localhost' (using password: YES)` and `Unknown database 'storage_mgt'` that doesn't happen on the v2.1 branch.

Otherwise, `mix test` and `MIX_ENV=pg mix test` all passed.

**Comment by josevalim** [comment] 2017-05-27 13:05
@seantanly the problem with the commit above is that autogenerated fields are not applied even when we insert a whole new entry to the database. I believe we would need to know from the database if we got an insert or an update.

**Comment by seantanly** [comment] 2017-05-27 14:04
> the problem with the commit above is that autogenerated fields are not applied even when we insert a whole new entry to the database.

I checked, the autogenerated fields e.g. inserted_at/updated_at have their values persisted to the database.

I'm failing to understand why is there is a need to automatically return the autogenerated fields (not specified in returning, nor having read_after_writes: true) in the struct even when it's an insert, in the context of a upsert operation. May I know why?

**Comment by josevalim** [comment] 2017-05-27 14:08
Because that's how it works for successful operations on insert without upsert. And such change would also be backwards incompatible.

I would also like to hear arguments on the opposite direction. Again, I find the argument that the autogenerated fields are out of date to be weak, because *all fields are potentially out of date*. If not merging them can help avoid the confusion, then sure, but I wouldn't go as far as to say it is the preferred behaviour even when insert succeeds.

**Comment by seantanly** [comment] 2017-05-27 15:51
Let's set the context to be that the autogenerated values are not defined in returning nor having read_after_writes: true.

The argument is not about out-of-date values, be it insert or update during upsert. It is about the autogenerated fields currently returned when it's an update, is just wrong because they are never persisted to the database in the first place. Non-concurrent access would have expected the returned values to be reflective of the current state of the record in DB after upsert. I believe this is acknowledged and thus the opening of the new issue.

I'm suggesting a different behavior when upsert is in play, making the user be explicit in the expected returned fields instead of the usual insert behavior.

--

Let's we say we can determine whether it's an update or insert. And when it's an update, we make all the autogenerated values be empty. 

For PG users, it might not be useful. Should there will be a code path to check for nil autogenerated values, and issue a new SELECT to get the required fields from the DB, or is it easier to just define the required fields in `returning` or having `read_after_writes: true` and have a single code path?

I can see the pt for MySQL users, they don't have `returning` and `read_after_writes` except for primary key. Having the ability to determine whether an update occurred will allow they to optimize,  issuing a new SELECT for data when it's an update, and not when it's an insert.

Noticed another gotcha with using autogenerated values with upsert. The usual Ecto handled `updated_at` will not update as usual during update in upsert. `Schema.timestamps` is a common use case.

Given all these considerations, imo upsert is quite different from the conventional insert. I'm wondering whether we're trying too hard to shoehorn upsert to behave like insert out-of-the-box? Isn't checking for update in upsert via empty autogenerated field pushing too far in that direction too?

**Comment by josevalim** [comment] 2017-05-27 16:28
> It is about the autogenerated fields currently returned when it's an update, is just wrong because they are never persisted to the database in the first place

I believe we are going into loops here. That's true for any other field set in the struct before the `insert` call. It is not about concurrency. If you set `%{post | foo: "bar"}`, in case of upsert it is impossible to know if the value in the database for "foo" will be "bar" or not. That's because databases like Postgres does not actually let us know which operation (insert or update) happened in case of upserts. And autogenerated fields are just fields that are set before a database operation. 

Surprisingly, MySQL does allow us to know if an insert or update happened, but only because it mistakenly says two rows were affected by the insert.

So given Postgres does not give us enough information, I will have to close the new issue too. If you want to make sure your information is up to date in case of upserts, then you have to use `returning: true` and we are not going to impose that as a default because it is not compatible with all adapters.

**Comment by josevalim** [comment] 2017-05-27 16:31
And to add to that, we cannot make upserts not apply auto generated fields by default because that breaks the expectation with insert. And it still does not make it possible to know which operation succeeded. You need to use return or issue a new query.

**Comment by josevalim** [comment] 2017-05-27 16:37
Sorry, one extra comment. The way I see it, the only mechanism that could potentially benefit from this change is `on_conflict: :nothing`. Maybe then it would be reasonable to not apply any autogenerated field because it is the only scenario we can actually detect if an insert or nothing happened and returning autogenerated fields actually makes it not possible. So I will create a new issue to not apply autogenerated values for `on_conflict: :nothing`. What do you think?

**Comment by josevalim** [comment] 2017-05-27 17:12
Actually, MySQL does not let us make a distinction between an insert and nothing. :'(

**Comment by seantanly** [comment] 2017-05-27 18:44
Thanks for the explanation, earlier on I missed out that the all fields set in struct are returned, not just autogenerated ones. 

Trying to summarize what has being said,

1. In simple insert, `{:ok, struct}`, fields in struct represents values that were persisted to DB. Values may already be stale.
2. In upsert, `{:ok, struct}`, if an insert occurred, fields in struct represents values that were persisted to DB. Values may already be stale.
3. In upsert, `{:ok, struct}`, if an update occurred, fields in struct **do not** represent the values that persisted to DB. Values cannot be relied upon. Exception: Primary key is valid if managed by the DB.
4. In upsert, `{:ok, struct}`, in determining insert or update has occurred - for PG is not possible, for MySql is possible by relying on a bug. **?Without knowing whether it's an insert/update during upsert, thus as a general rule the fields in struct cannot be relied upon during upsert?** Exception: Primary key is valid if managed by the DB.
5. To mitigate pt 4, PG users can make use of `returning` (`read_after_writes: true` is still in play). MySQL users has to issue a new query.
6. In upsert `on_conflict: :nothing`, `{:ok, struct}`, in determining insert or nothing has occurred - PG is possible, MySQL not possible. If we know the op is insert, the fields in struct represents values that were persisted to DB. Values may already be stale. **?However there is not much to gain for PG users since `returning` and `read_after_writes: true` is available to them?**

Condensing, 
1. For simple inserts and inserts in upserts, values in returned struct are valid but maybe stale. 
2. For updates in upserts, values in returned struct are not valid unless using facilities like `returning`  or `read_after_writes: true`. Exception: primary key is valid if managed by the DB. 
3. Not all DB adapters support pt2 facilities. Unsupported adapter e.g. MySQL users to issue a new query to obtain values.

As a general rule for upserts, to consistently obtain valid field values, 
1. Adapters supporting `returning`  or `read_after_writes: true` such as PG should make use it. 
2. Other adapters' users should issue a new query for field values.

**Comment by josevalim** [comment] 2017-05-27 18:57
Yes, that's a good summary! I have updated the docs meanwhile and pushed to master and I think we cover all of those cases.

**Comment by mortezaKcode** [comment] 2019-03-05 21:55
> @alex88 yes, sorry, returning doesn't work for insert, only insert_all. This should be fixed if you set read_after_writes: when defining the binary_id.
> 
> ```
> @primary_key {:id, :binary_id, autogenerate: true, read_after_writes: true}
> ```
> That's what the `:id` key does by default.

hey ,what should i do for  this one : 
insert comment if post exist
