### ISSUE TITLE
Inconsistent behavior of (in?)valid Ecto.Query

### ISSUE THREAD

**Issue by mpranjic** [elixir-ecto/ecto#2043] opened 2017-04-25 23:49 UTC
Sorry for a bad title, please change to something more appropriate ^_^

### Environment

* Elixir version (elixir -v): 1.4.2
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): postgresql 9.6.1
* Ecto version (mix deps): **master branch**
* Database adapter and version (mix deps): postgrex 0.13.2
* Operating system: ArchLinux

### Current behavior

To demonstrate the issue, you can make changes to the `integration_test/cases/repo.exs`.
Append the following check after line 28:
```
test "fetch empty" do # this is line 28
  assert [] = TestRepo.all from p in Post, where: p.title in ^nil
  ...
```

When running the test, I get the following error:
```
$ MIX_ENV=pg mix test integration_test/cases/repo.exs:28

Including tags: [line: "28"]
Excluding tags: [:test]



  1) test fetch with in (Ecto.Integration.RepoTest)
     integration_test/cases/repo.exs:28
     ** (ArgumentError) argument error
     stacktrace:
       :erlang.length(nil)
       (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
       (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
       (ecto) lib/ecto/repo/queryable.ex:122: Ecto.Repo.Queryable.execute/5
       (ecto) lib/ecto/repo/queryable.ex:35: Ecto.Repo.Queryable.all/4
       integration_test/cases/repo.exs:30: (test)



Finished in 1.1 seconds
92 tests, 1 failure, 91 skipped

Randomized with seed 498057
```

Now, let's add a valid query before the one above:
```
test "fetch empty" do
  assert [] = TestRepo.all from p in Post, where: p.title in ^[]
  assert [] = TestRepo.all from p in Post, where: p.title in ^nil
  ...
```

Result? Test passes.

```
$ MIX_ENV=pg mix test integration_test/cases/repo.exs:28

Including tags: [line: "28"]
Excluding tags: [:test]

.

Finished in 1.1 seconds
92 tests, 0 failures, 91 skipped

Randomized with seed 611531

```

### Expected behavior

Consistency - it should either fail or not fail.

#### Additional info

This is bugging me in my Phoenix app, but I managed to reduce it to the minimal example, as seen above. It is reproducable in iex. You can't run invalid query (the one with ^nil), but after you run the other one, you can successfully run the first one as well.

**Comment by michalmuskala** [comment] 2017-04-26 07:01
On first sight, it looks like it's related to the query cache. 

@mpranjic could you provide the logger output? I'm primarily interested in what queries end up being executed against the database in the second case.

**Comment by mpranjic** [comment] 2017-04-26 07:13
```Interactive Elixir (1.4.2) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> import Ecto.Query
Ecto.Query
iex(2)> alias Pop.Repo
Pop.Repo
iex(3)> alias Pop.Library.Tag
Pop.Library.Tag
iex(4)> query1 = from t in Tag, where: t.id in ^nil
#Ecto.Query<from t in Pop.Library.Tag, where: t.id in ^nil>
iex(5)> query2 = from t in Tag, where: t.id in ^[] 
#Ecto.Query<from t in Pop.Library.Tag, where: t.id in ^[]>
iex(6)> Repo.all query1
** (ArgumentError) argument error
             :erlang.length(nil)
    (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
iex(6)> Repo.all query2
[debug] QUERY OK source="tag" db=0.7ms
SELECT t0."id", t0."type", t0."name", t0."is_disabled", t0."inserted_at", t0."updated_at" FROM "tag" AS t0 WHERE (t0."id" = ANY($1)) [[]]
[]
iex(7)> Repo.all query1
[debug] QUERY OK source="tag" db=2.5ms
SELECT t0."id", t0."type", t0."name", t0."is_disabled", t0."inserted_at", t0."updated_at" FROM "tag" AS t0 WHERE (t0."id" = ANY($1)) [nil]
[]

```

**Comment by mpranjic** [comment] 2017-04-26 07:44
I think it should be a valid query because (at least in postgres) this is valid:

```
select * from tag where tag.id = ANY(NULL);
```

But I am under impression that query cache is doing something wrong as well.

**Comment by nauger** [comment] 2017-06-24 23:26
We have a failing test, that happens inconsistently that appears to be related to the above.

Elixir: 1.3.4
Ecto: 2.1.4

**Comment by josevalim** [comment] 2017-08-06 18:13
> I think it should be a valid query because (at least in postgres) this is valid:

The underlying query we compile into is more of an implementation default. It could have been `foo IN NULL` which is not valid. Plus raising on nil makes it consistent across adapters, so I would rather consistently raise.

I have pushed a fix to master. Thanks for the report with the perfectly reproducible case!

**Closed** 2017-08-06 18:13 UTC
Labels: Kind:Bug, Level:Advanced
