### ISSUE TITLE
Can't run integration tests for ecto master

### ISSUE THREAD

**Issue by anthonator** [elixir-ecto/ecto#2675] opened 2018-08-31 19:23 UTC
### Environment

* Elixir version (elixir -v): 1.7.3
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 10.5
* Ecto version (mix deps): 3.0.0-dev
* Database adapter and version (mix deps): Postgrex 0.14.0-dev
* Operating system:
```
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
```

### Current behavior

Whenever I run `mix test.all` I get the following error:

```
19:15:24.555 [error] GenServer #PID<0.249.0> terminating
** (ArgumentError) argument error
    :erlang.element(1, :error)
    (postgrex) lib/postgrex/utils.ex:66: anonymous fn/1 in Postgrex.Utils.parse_version/1
    (elixir) lib/enum.ex:1314: Enum."-map/2-lists^map/1-0-"/2
    (elixir) lib/enum.ex:1314: Enum."-map/2-lists^map/1-0-"/2
    (postgrex) lib/postgrex/utils.ex:66: Postgrex.Utils.parse_version/1
    (postgrex) lib/postgrex/protocol.ex:663: Postgrex.Protocol.bootstrap_send/6
    (postgrex) lib/postgrex/protocol.ex:497: Postgrex.Protocol.handshake/2
    (db_connection) lib/db_connection/connection.ex:134: DBConnection.Connection.connect/2
Last message: nil
```

If I try upgrading Postgrex I get a dependency mismatch error for `db_connection`. Overriding `db_connection` results in another series of errors.

### Expected behavior

Tests should execute successfully.

**Comment by fishcakez** [comment] 2018-08-31 19:33
Try postgrex 0.13.5, its expected that master of postgrex does not work right now.

**Comment by josevalim** [comment] 2018-08-31 19:36
@fishcakez the issue is that Postgres 10 changed the versioning schema. I am not sure if we tackled this in Postgrex master but this is definitely a Postgrex bug. @anthonator, can you please report it here: https://github.com/elixir-ecto/postgrex Thanks!

**Comment by fishcakez** [comment] 2018-08-31 19:46
Didnt we fix this in postgrex 0.13.5?

**Comment by josevalim** [comment] 2018-08-31 19:47
@fishcakez it would be weird if postgrex master is behind 0.13.5. I will investigate.

**Comment by anthonator** [comment] 2018-08-31 19:47
I can confirm downgrading to Postgres 9.6 fixes the issue.

**Comment by josevalim** [comment] 2018-08-31 19:50
This will be fixed when we update Postgrex. It is just tricky to do because Postgrex latest depends on DBConnection latest, but we need to update Mariaex first.

**Comment by fishcakez** [comment] 2018-08-31 19:52
@josevalim I think we could add refs to the deps to make build pass.

**Comment by josevalim** [comment] 2018-09-01 07:14
Tackled in #2677 although it is still WIP (had some failing tests).

**Closed by josevalim** 2018-09-01 07:14 UTC
