### ISSUE TITLE
Warning about duplicated primary keys for new records

### ISSUE THREAD

**Issue by feliperenan** [elixir-ecto/ecto#3514] opened 2020-12-16 15:17 UTC
### Environment

* Elixir version (elixir -v): 1.11.1
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 13.1
* Ecto version (mix deps): 
* Database adapter and version (mix deps):
* Operating system:

### Current behavior

Ecto warns about duplicated keys even though associations are being inserted for the first time:

```Elixir
alias EctoIssue.TODO.{Item, List}

list = %List{items: [%Item{}, %Item{}]}

list_attrs = %{
  "title" => "my list",
  "items" => %{
    "0" => %{"name" => "item-1"},
    "1" => %{"name" => "item-2"}
  }
}

changeset = List.changeset(list, list_attrs)
#Ecto.Changeset <...>
```

Then Ecto warns about his:

```
[warn] found duplicate primary keys for association/embed `:items` in `EctoIssue.TODO.List`. In case of duplicate IDs, only the last entry with the same ID will be kept. Make sure that all entries in `:items` have an ID and the IDs are unique between them
```

I have also created this sample app that reproduces this issue: https://github.com/feliperenan/ecto_issue

### Expected behavior

I believe this warning shouldn't happen when creating new record since they don't have ids yet. Let me know if that is expected or I'm missing something 🙌🏻 .

**Comment by josevalim** [comment] 2020-12-16 15:31
@feliperenan we are probably checking the nil values and since we have two nils, it is raising. Would you like to send a PR? :)

**Comment by feliperenan** [comment] 2020-12-16 15:47
I'd be happy open a PR for that 👍🏻 

I have just noticed something else. The first item present in the`changeset` returned from my example above has the action as `:update` since I'm using a `List struct` with two empty `Item`.

```elixir
iex(176)> changeset = List.changeset(list, list_attrs)
[warn] found duplicate primary keys for association/embed `:items` in `EctoIssue.TODO.List`. In case of duplicate IDs, only the last entry with the same ID will be kept. Make sure that all entries in `:items` have an ID and the IDs are unique between them

#Ecto.Changeset<
  action: nil,
  changes: %{
    items: [
      #Ecto.Changeset<
        action: :update,
        changes: %{name: "item-1"},
        errors: [],
        data: #EctoIssue.TODO.Item<>,
        valid?: true
      >,
      #Ecto.Changeset<
        action: :insert,
        changes: %{name: "item-2"},
        errors: [],
        data: #EctoIssue.TODO.Item<>,
        valid?: true
      >
    ],
    title: "my list"
  },
  errors: [],
  data: #EctoIssue.TODO.List<>,
  valid?: true
>
```

So I can't perform an insert on this `changeset`. Now I'm wondering if that make sense at all to send a `List` with two empty `Items`. In my use case, I do that because I want to display two items in the first render so Users can remove/add more items on top of that - but maybe I should make sure that I'm performing validations against an `List` without items since those items will be present on the `list_params` anyway 🤔

**Comment by josevalim** [comment] 2020-12-16 16:22
It would only be marked as `update` if it thinks it already has an associated entry and this associated entry has a nil `id`. So I think the issue is actually that you have a non persisted item in the list you are passing to changeset. If you remove that, then everything should work and the warning should disappear too.

**Comment by v0idpwn** [comment] 2020-12-17 00:44
Why does Ecto assumes there's an associated entry? Shouldn't all actions be `:insert`?

**Comment by feliperenan** [comment] 2020-12-18 08:54
Yes, for the simple fact I'm sending an empty struct, Ecto tries to get the PK anyway and reduces the `items` structs to one because both will have the same "id" at this moment, which is nil.

You can see this happening here: 

https://github.com/elixir-ecto/ecto/blob/2568da2ef8bd6ec180717c37350e1d16e7cd09cf/lib/ecto/changeset/relation.ex#L439-L443

If somehow, we ignore that `current` with pk `nil` that arrives to this `process_current/3` function, that would behave as an `insert` for both items. But I'm not 100% sure if that makes sense though 🤔 .

Just to exemplify with code, something like that:

```Elixir
      Enum.map_reduce(current, {%{}, 0}, fn struct, {acc, counter} ->
        struct
        |> get_pks.()
        |> Enum.reject(&is_nil/1)
        |> case do
          [] ->
            {[], {%{}, 0}}

          pks ->
            key = if pks == [], do: map_size(acc), else: pks
            {pks, {Map.put(acc, key, struct), counter+ 1}}
        end
      end)
```

Or, somehow some step before this function is called.

Anyway, I was able to solve my this issue in my current app without any work around, so feel free to close this one. Or let me know if you think we need to do something here 🙌🏻 .

Thanks

**Comment by josevalim** [comment] 2020-12-18 09:45
@feliperenan to be clear, I think the issue is not on Ecto but on the struct. When you call put_assoc/put_embed, does the List struct has any `items` already associated to it besides the ones given to put_assoc/put_embed?

**Comment by feliperenan** [comment] 2020-12-18 11:18
> When you call put_assoc/put_embed, does the List struct has any items already associated to it besides the ones given to put_assoc/put_embed?

If I get it right, It does, even though they are all empty structs (all keys as nil).

```elixir
list = %List{items: [%Item{}, %Item{}]}

list_attrs = %{
  "title" => "my list",
  "items" => %{
    "0" => %{"name" => "item-1"},
    "1" => %{"name" => "item-2"}
  }
}

changeset = List.changeset(list, list_attrs)
```

So, `Ecto` understands that we are trying to update those items and one of them will have the action as `update`. 

I feel I'm kind confused with that and I thought I had fixed that on my app, but I don't. Now, I think it is an Ecto issue 🙈 

 I'd be happy to show this issue for you in a video call if that is fine by you.

**Comment by josevalim** [comment] 2020-12-18 11:36
Right, that's my point, don't put those items in there. If you are generating those items but you want to show them empty in your views, then build them in your view, but do not pass to the list you are giving to changeset. Ecto works with the assumption that whatever struct you give to `Ecto.Changeset` is correct, which doesn't hold if you are injecting empty structs in there. :)

**Closed by josevalim** 2020-12-18 11:36 UTC

**Comment by feliperenan** [comment] 2020-12-18 12:20
As always, thank you for clarifying 💪🏻
