### ISSUE TITLE
Ecto handle Postgres Arrays of JSONB `field(:reco, {:array, :map}` really really slow

### ISSUE THREAD

**Issue by Sebisnow** [elixir-ecto/ecto#3801] opened 2021-12-14 11:48 UTC
### Environment

* Elixir version (elixir -v):1.13.0
* Database and version: PostgreSQL 12.4
* Ecto version (mix deps): 3.7.1
* Database adapter and version (mix deps): postgrex 0.15.13
* Operating system: Ubuntu 20.04, 

### Current behavior
https://elixirforum.com/t/ecto-embedded-schemas-really-really-slow-4sec-for-150-db-entries-and-its-not-the-db/44405
We use Elixir in a couple of Microservices. One of them Stores Information about Reservations placed for different stores. Fetching all reservations for a store in a certain timeframe used to be really fast (with little reservations) but with 150 reservations returned the performance decreases to a steady 4 seconds… For a Team that prides themselves in time in service durations of on average less than 60ms, that is tough…
I took all day to narrow it down and it seems to me that the bottleneck is the result mapping from the Database to the final Elixir structs. The Postgres DB Queries are always below 10ms but what happens afterwards is a mystery to me…

Here some insights into the Schemas involved. The DB Schema for reservation events looks like:
```elixir
  schema "reservation_events" do
    field(:reservation_id, :string)
    field(:status, :string)
    field(:start, :utc_datetime_usec)
    field(:store_id, :integer)
    field(:hash, :string)
    field(:customer, EncryptedCustomerReservation)
    embeds_many(:products, Product)
    embeds_many(:reco, Product)
    field(:confirmation_timestamp, :utc_datetime_usec)
    field(:confirmation_store_timestamp, :utc_datetime_usec)
    field(:locale, :string)
    field(:mandator_id, :string)
    timestamps()
  end
```
The EncryptedCustomerReservation implements the Ecto.Type behaviour and maps a Customer (Map consisting of Name, Email, Telephone, …) to a JSON String and encrypts that at rest (dump/1) and decrypts it at need/read (load/1). Always done in under 1ms.
The encrypt function called on dump for the Customer:
```elixir
  def encrypt(reservation) do
    :crypto.crypto_one_time(
      :aes_256_ctr,
      @key,
      @init_vector,
      reservation |> Jason.encode!() |> Base.encode64() |> to_charlist,
      true
    )
    |> to_string
  end
```
Decrypting is simplyfied the reverse of the above.

The Product part is an embedded_schema (JSONB) but I also went the way to implement the Ecto.Type behaviour to get a better introspection. I implemented the load callback as follows:
```elixir
def load(data) when is_map(data) do
    start = DateTime.utc_now
    data =
      for {key, val} <- data do
        {String.to_existing_atom(key), val}
      end

    {:ok, struct!(Product, data)}
  end
```
Probably not the most beautiful way but the performance stayed pretty much the same. Every Product load is again finished in under 1ms.

The Product schema:
```elixir
  use Ecto.Schema
  embedded_schema do
    field :url
    field :image
    field :text
    field :price
    field :currency
    field :reasonCanceled
    field :status
  end
```
Since all reservations currently only have one product and all mappings from db to Elixir structs take less than 1ms for 160 entries this should never ever take 4 seconds. Probably not even 160ms.

I also removed the abstraction layer with embeds_many and used `field(:reco, {:array, :map}` directly with no change in performance. Therefore the bottleneck is not how we implement the load from db but how ecto handles the mapping from postgres output format to Elixir data format.

### Expected behavior

Ecto should be able to map Postgres Array of JSONB quickly in milliseconds rather than in seconds

### Workaround

Currently I query the Database 'directly' in order to map the db result myself:
```elixir
result = Stores.Repo.query!(
        "select * from reservation_events where store_id = '#{store_id}' and timestamp '#{date.year}-#{date.month}-#{date.day}' >= start and timestamp '#{start_date.year}-#{start_date.month}-#{start_date.day}' <= start;"
result.rows
|> Enum.map(&map_db_to_output(result.columns, &1, store))
```
```elixir
def map_db_to_output(row, columns, store) do
    Stream.zip(row, columns)
    |> Enum.into(%{})
    |> format_event_data!(store)
  end

def format_event_data!(
        %{
          "customer" => customer,
          "products" => products,
          "reco" => reco,
          "reservation_id" => reservation_id,
          "start" => start,
          "status" => status,
          "store_id" => store_id
        },
        city
      ) do
    %{
      "reservationId" => reservation_id,
      "status" => status,
      "start" => start,
      "storeId" => store_id,
      "storeName" => city,
      "customer" => Stores.Encryption.EncryptedCustomerReservation.decrypt(customer),
      "products" => products,
      "reco" => reco
    }
  end
```

**Comment by josevalim** [comment] 2021-12-14 11:58
Without a mechanism to reproduce the slow down, it is hard for us to pin point exactly what is wrong. Therefore, can you please provide a minimal application that reproduces the error?

**Comment by greg-rychlewski** [comment] 2021-12-20 02:20
@Sebisnow It could be that your JSONs are very large and take a while to (de-)serialize going from Postgres -> App -> HTTP response. You could run a profiler to see how much time is being spent on (de-)serialization.

My team was in a similar situation in the past and implemented the following work around:
  - Define the field in Postgres as a string instead of JSONB
  - Define a custom Ecto Type that takes maps and encodes them to JSON before saving to the database but keep it as a string on the way out from the database
 
This worked for us because we only had to serve bulky GET requests  and this helped us bypass the (de-)serialization. We didn't need to query our database for specific fields in the JSON, only needed to pull the whole thing. And when we wanted to update the JSON it wasn't in such a bulk quantity.

Your situation may be different, but thought I'd throw this out there.

**Comment by Sebisnow** [comment] 2021-12-20 18:28
Thanks for both your replys. Currently I am very short of time. The JSONs are actually pretty small. The biggest in the DB is currently an Array of three JSONs with six key value pairs. That's it. 

Currently my workaround is to not use Ecto for this specific DB query but to use Postgrex directly and zip the columns and rows together myself. That's really fast by comparison.

**Comment by josevalim** [comment] 2022-04-15 05:44
Closing for now. If you find a way to reproduce this issue , please let us know, and will gladly reopen it.

**Closed** 2022-04-15 05:45 UTC
Labels: Note:Needs more info
