### ISSUE TITLE
Unexpected string encoding change from UTF-8 to UTF-16 when using Ecto.Query

### ISSUE THREAD

**Issue by roehst** [elixir-ecto/ecto#1923] opened 2017-01-22 22:42 UTC
Hi, can anyone help me with Ecto? I am having what appears to me to be pretty odd with string encodings. This is weird because it is very unexpected behavior from my pont if view as a developer.

### EXPECTED BEHAVIOR

I want to build a query which includes the character "á", which has different encodings depending on whether it is UTF-8/UTF-16 using Ecto.Query and run it.

    query = from "questions", select: fragment("correct"), where: fragment("subject = 'Matemática'")

I should get some rows as a result.

### ACTUAL BEHAVIOR 

If I run the query, I get a Postgres error related to encoding.

    iex(13)> Repo.all query
    ** (Postgrex.Error) ERROR 22021 (character_not_in_repertoire): invalid byte sequence for encoding "UTF8": 0xe1 0x74 0x69
    [debug] QUERY ERROR source="questions" db=0.5ms
    SELECT correct FROM "questions" AS q0 WHERE (subject = 'Matem�tica') []
        (ecto) lib/ecto/adapters/sql.ex:436: Ecto.Adapters.SQL.execute_and_cache/7
        (ecto) lib/ecto/repo/queryable.ex:130: Ecto.Repo.Queryable.execute/5
        (ecto) lib/ecto/repo/queryable.ex:35: Ecto.Repo.Queryable.all/4

### SOME DEBUGGING I DID

This is bad because it should just work. Let's do some debugging, say, let's
see what comes out from Ecto:

    {raw_query, []} = Ecto.Adapters.SQL.to_sql :all, Repo, query
    File.write "raw_query.sql", raw_query

Then I load the "raw_query.sql" file on Sublime and I see that it is NOT in UTF-8. It shows up validly as "ISO 8859-1", and we see that because the "á" in "Matemática" is encoded as 0xe1 in the byte-by-byte representation:

    5345 4c45 4354 2054 5255 4520 4652 4f4d
    2022 7175 6573 7469 6f6e 7322 2041 5320
    7130 2057 4845 5245 2028 7375 626a 6563
    7420 3d20 274d 6174 656d [e1] 74 6963 6127
    29

Let's validate against using "á" not going through Ecto:

    File.write "raw_term", "Matemática"

When I open the "raw_term" file, I get the following, which is UTF-8:

    4d61 7465 6d[c3] [a1]74 6963 61

Here, "á" is encoded by 0xC3 0xA1.

So, I don't know why, but Ecto is somehow "rendering" the query in "ISO 8859-1": if I print the string directly to a file, I get the UTF-8 representation, but if I use it within a query, Ecto will turn it into "ISO 8859-1".

Back to the query. If I do it without Ecto, it works:

    iex(13)> Repo.query "SELECT correct FROM \"questions\" AS q0 WHERE (subject = 'Matemática')"
    [debug] QUERY OK db=1.9ms queue=0.1ms
    SELECT correct FROM "questions" AS q0 WHERE (subject = 'Matemática') []
    {:ok,
     %Postgrex.Result{columns: ["correct"], command: :select,
      connection_id: 10112, num_rows: 4,
      rows: [["false"], ["false"], ["false"], ["false"]]}}

So I am really guessing Ecto is changing the encoding to "ISO 8859-1".

### MORE INFO

For more information on the "á" character and its code points encodings etc, see: 

http://www.fileformat.info/info/unicode/char/00e1/index.htm

### SEED FOR THE DATABASE

The seed for the table I am querying against is:

    drop table if exists questions;
    create table questions (correct TEXT, subject TEXT);
    insert into questions values (false, 'Matemática');
    insert into questions values (false, 'Matemática');
    insert into questions values (false, 'Matemática');
    insert into questions values (false, 'Matemática');
    insert into questions values (false, 'Outro assunto');
    insert into questions values (false, 'Outro assunto');
    insert into questions values (false, 'Outro assunto');
    insert into questions values (false, 'Outro assunto');

**Comment by roehst** [comment] 2017-01-22 22:44
ps. I am not sure my understanding of encodings is right. This was the first time I dealed with it.

**Comment by josevalim** [comment] 2017-01-22 22:49
When you open up an issue, we ask for a bunch of information to be filled. Please send this information, otherwise we can't help you.

**Comment by roehst** [comment] 2017-01-22 22:54
Elixir version:

➜  ~ elixir -v
Erlang/OTP 19 [erts-8.2] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.4.0

PostgreSQL version:

➜  ~ psql -d xx -c 'select version()';
                                        version                                        
---------------------------------------------------------------------------------------
 PostgreSQL 9.6.1 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 6.2.1 20160830, 64-bit
(1 row)

Dependencies: (ecto, phoenix_ecto, postgrex)

* postgrex 0.13.0 (Hex package) (mix)
  locked at 0.13.0 (postgrex) e101ab47
  ok
* ecto 2.1.1 (Hex package) (mix)
  locked at 2.1.1 (ecto) fa8bdb14
  ok
* phoenix_ecto 3.0.1 (Hex package) (mix)
  locked at 3.0.1 (phoenix_ecto) 42eb486e
  ok

operating system:

Arch Linux 

➜ uname -a    
Linux x 4.8.13-1-ARCH #1 SMP PREEMPT Fri Dec 9 07:24:34 CET 2016 x86_64 GNU/Linux

**Comment by josevalim** [comment] 2017-01-22 23:27
I checked your info. Everything seems to be correct. Could it be that the file for that particular query is with wrong encoding? For example, go back to the query that fails and do `inspect query` before running it against the repository. What does it return?

**Comment by roehst** [comment] 2017-01-22 23:35
This was all run from IEX, so I don't think the file containing the query has the incorrect encoding.

I will try this on a clean phoenix install again and see if I get any different behavior.

iex(4)> query = from "questions", select: fragment("correct"), where: fragment("subject = 'Matemática'")
#Ecto.Query<from q in "questions",
 where: fragment(<<115, 117, 98, 106, 101, 99, 116, 32, 61, 32, 39, 77, 97, 116, 101, 109, 225, 116, 105, 99, 97, 39>>),
 select: fragment("correct")>

iex(5)> inspect query
"#Ecto.Query<from q in \"questions\", where: fragment(<<115, 117, 98, 106, 101, 99, 116, 32, 61, 32, 39, 77, 97, 116, 101, 109, 225, 116, 105, 99, 97, 39>>), select: fragment(\"correct\")>"

**Comment by josevalim** [comment] 2017-01-22 23:36
From the printed query we can see that it is not valid UTF-8 since we see it as a binary fragment. What happens if you just type "Matemática" in IEx?

**Comment by roehst** [comment] 2017-01-22 23:37
Fresh new phoenix repo.

➜  weird_bug_ecto iex       
Erlang/OTP 19 [erts-8.2] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false]

Interactive Elixir (1.4.0) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)>  "Matemática"
"Matemática"
iex(2)>

**Comment by josevalim** [comment] 2017-01-22 23:41
But the query also fails to inspect in the fresh new Phoenix repo?!

**Comment by roehst** [comment] 2017-01-22 23:43
I am packaging this as a repo and will push to github in a second. So it gets fully reproducible.

**Comment by josevalim** [comment] 2017-01-22 23:49
Don't worry, I can reproduce the issue. :)

**Comment by josevalim** [comment] 2017-01-22 23:52
As a quick fix, you can write your query this way:

    query = from "questions", select: fragment("correct"), where: fragment("subject = ?", "Matemática")

**Comment by roehst** [comment] 2017-01-22 23:52
The query inspects as a binary in the new phoenix repo.

**Comment by josevalim** [comment] 2017-01-22 23:53
Thank you for the bug report and information to reproduce the issue. It has been fixed in master! 
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Closed by josevalim** 2017-01-22 23:53 UTC

**Comment by roehst** [comment] 2017-01-22 23:54
@josevalim Obrigado pela ajuda incrivelmente rápida.

**Comment by roehst** [comment] 2017-01-23 00:03
@josevalim How does this get pushed down to the phoenix_ecto package so I can update my project?

**Comment by josevalim** [comment] 2017-01-23 08:32
You can specify Ecto directly as a dependency as:

    {:ecto, github: "elixir-ecto/ecto", branch: "v2.1", override: true}

**Comment by msp** [comment] 2017-07-30 16:21
@josevalim - Is there a similar bug on insertion too? 

https://github.com/msp/cenatus-ltd/commit/1f71391ad665931436d9357ab79e5757cb0274cb

```
1) test authorized routes creates resource and redirects when data is valid (non UTF8) (CenatusLtd.ArticleControllerTest)
     test/controllers/article_controller_test.exs:32
     ** (Postgrex.Error) ERROR 22021 (character_not_in_repertoire): invalid byte sequence for encoding "UTF8": 0xc3 0x2d
     stacktrace:
       (ecto) lib/ecto/adapters/sql.ex:571: Ecto.Adapters.SQL.struct/7
       (ecto) lib/ecto/repo/schema.ex:467: Ecto.Repo.Schema.apply/4
       (ecto) lib/ecto/repo/schema.ex:205: anonymous fn/13 in Ecto.Repo.Schema.do_insert/4
       (ecto) lib/ecto/repo/schema.ex:684: anonymous fn/3 in Ecto.Repo.Schema.wrap_in_transaction/6
       (ecto) lib/ecto/adapters/sql.ex:620: anonymous fn/3 in Ecto.Adapters.SQL.do_transaction/3

``

**Comment by Trevoke** [comment] 2017-09-12 17:32
Is this fixed in 2.2.1? I am running into this error occasionally.

**Comment by ryanwinchester** [comment] 2017-12-15 03:18
I'm also getting this error when trying to store encrypted fields in ecto, using this:

http://blog.danielberkompas.com/elixir/security/2015/07/03/encrypting-data-with-ecto.html

**Comment by fishcakez** [comment] 2017-12-15 04:13
Yes, it is fixed in v2.2.0-rc.0 onwards. It has also been backported to v2.1 branch but we have not released a 2.1 patch that includes it.

**Comment by Ox90** [comment] 2018-02-01 22:09
Hi, @fishcakez how we can get this patch in 2.1?

**Comment by josevalim** [comment] 2018-02-02 00:16
You can use the 2.1 branch. It is unlikely we will do a new 2.1 release.

**Comment by Ox90** [comment] 2018-02-02 14:07
Hi, well at this point dont know if its about ecto or the adapter... 
I attach a demo proyect, i apretiate any hint.

running on 

Erlang/OTP 20 [erts-9.0] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10]

Elixir 1.5.2

MSSQL 

CREATE TABLE tests (id int NOT NULL, [name] varchar(60) NOT NULL)
INSERT INTO tests VALUES (1, '"príeba áctúalizar"')

then

mix phx.new try_c --no-html --no-brunch --database mssql
mix phx.gen.json Tests Test tests name:string

[try_c.zip](https://github.com/elixir-ecto/ecto/files/1689571/try_c.zip)

and 
http://localhost:4000/api/tests
get this...

![error](https://user-images.githubusercontent.com/19688500/35736983-9bd6a494-07ef-11e8-9af2-645c80a3747f.PNG)
