### ISSUE TITLE
:gen_server.call(#PID<0.307.0>, {:checkout,  ...... ** (EXIT) time out

### ISSUE THREAD

**Issue by GildedHonour** [elixir-ecto/ecto#2600] opened 2018-06-20 10:51 UTC
I have a Phoenix app. All of a sudden this issue has begun appearing:

      [error] #PID<0.432.0> running MyAppWeb.Endpoint terminated
      Server: localhost:4000 (http)
      Request: GET /articles/article123
      ** (exit) exited in: :gen_server.call(#PID<0.307.0>, {:checkout, #Reference<0.3524641702.649854977.121112>, true, 15000}, 5000)
          ** (EXIT) time out

mix.exs:

      # ......

      {:phoenix, github: "phoenixframework/phoenix", override: true},
      {:phoenix_pubsub, "~> 1.0"},
      {:phoenix_ecto, "~> 3.2"},
      {:postgrex, "~> 0.13.5"},

        # ......

I've reseted my db. No luck.

**Comment by michalmuskala** [comment] 2018-06-20 10:59
Possible duplicate of https://github.com/elixir-ecto/db_connection/issues/127

**Comment by josevalim** [comment] 2018-06-20 11:56
Let's contine the discussion in the db_connection issue.

**Closed by josevalim** 2018-06-20 11:56 UTC
